import 'dart:convert';
import 'dart:io';

void main() async {
  final existingFile = File('assets/health_terms.json');
  List<dynamic> data = [];

  if (await existingFile.exists()) {
    final contents = await existingFile.readAsString();
    data = json.decode(contents);
  }

  print('Existing terms: \${data.length}');

  final newTerms = [
    // --- Anatomi & Fizyoloji (Anatomy & Physiology) ---
    {"e": "abdominal cavity", "t": "karın boşluğu", "c": "Anatomi", "x": "The liver is located in the upper right part of the abdominal cavity."},
    {"e": "adipose tissue", "t": "yağ dokusu", "c": "Anatomi", "x": "Excess adipose tissue is a key characteristic of obesity."},
    {"e": "aorta", "t": "aort", "c": "Anatomi", "x": "The aorta is the main artery that carries blood away from your heart."},
    {"e": "axilla", "t": "koltuk altı", "c": "Anatomi", "x": "Lymph nodes in the axilla are often examined for breast cancer spread."},
    {"e": "bile duct", "t": "safra kanalı", "c": "Anatomi", "x": "A gallstone can block the common bile duct, causing jaundice."},
    {"e": "blood-brain barrier", "t": "kan-beyin bariyeri", "c": "Fizyoloji", "x": "The blood-brain barrier protects the brain from harmful substances in the blood."},
    {"e": "brainstem", "t": "beyin sapı", "c": "Anatomi", "x": "The brainstem controls vital functions like breathing and heart rate."},
    {"e": "bronchiole", "t": "bronşçuk", "c": "Anatomi", "x": "Asthma causes the bronchioles to constrict, making breathing difficult."},
    {"e": "capillary", "t": "kılcal damar", "c": "Anatomi", "x": "Oxygen and nutrients are exchanged at the capillary level."},
    {"e": "cardiac muscle", "t": "kalp kası", "c": "Anatomi", "x": "Cardiac muscle tissue is found only in the heart."},
    {"e": "cerebrospinal fluid", "t": "beyin omurilik sıvısı", "c": "Anatomi", "x": "Cerebrospinal fluid acts as a cushion for the brain and spinal cord."},
    {"e": "cervix", "t": "rahim ağzı", "c": "Anatomi", "x": "The cervix is the lower part of the uterus that opens into the vagina."},
    {"e": "connective tissue", "t": "bağ dokusu", "c": "Anatomi", "x": "Connective tissue supports and binds other tissues in the body."},
    {"e": "coronary artery", "t": "koroner arter", "c": "Anatomi", "x": "A blockage in a coronary artery can lead to a heart attack."},
    {"e": "cranial nerve", "t": "kafa siniri", "c": "Anatomi", "x": "There are twelve pairs of cranial nerves that emerge directly from the brain."},
    {"e": "dermis", "t": "alt deri", "c": "Anatomi", "x": "The dermis contains blood vessels, hair follicles, and sweat glands."},
    {"e": "endocrine gland", "t": "iç salgı bezi", "c": "Anatomi", "x": "Endocrine glands secrete hormones directly into the bloodstream."},
    {"e": "epidermis", "t": "üst deri", "c": "Anatomi", "x": "The epidermis provides a waterproof barrier and creates our skin tone."},
    {"e": "epithelium", "t": "epitel doku", "c": "Anatomi", "x": "The epithelium lines the outer surfaces of organs and blood vessels."},
    {"e": "fallopian tube", "t": "fallop tüpü", "c": "Anatomi", "x": "Fertilization of an egg usually occurs in the fallopian tube."},
    {"e": "gallbladder", "t": "safra kesesi", "c": "Anatomi", "x": "The gallbladder stores bile produced by the liver."},
    {"e": "gastric juice", "t": "mide özsuyu", "c": "Fizyoloji", "x": "Gastric juice contains hydrochloric acid and digestive enzymes."},
    {"e": "gastrointestinal tract", "t": "mide-bağırsak yolu", "c": "Anatomi", "x": "The gastrointestinal tract is responsible for digesting and absorbing food."},
    {"e": "glottis", "t": "ses telleri arası boşluk", "c": "Anatomi", "x": "The glottis opens and closes during swallowing to prevent choking."},
    {"e": "hepatic vein", "t": "karaciğer toplardamarı", "c": "Anatomi", "x": "The hepatic veins transport deoxygenated blood from the liver to the vena cava."},
    {"e": "hypophysis", "t": "hipofiz bezi", "c": "Anatomi", "x": "The hypophysis is another name for the pituitary gland."},
    {"e": "ilium", "t": "leğen kemiğinin üst kısmı", "c": "Anatomi", "x": "The ilium is the uppermost and largest part of the hip bone."},
    {"e": "intervertebral disc", "t": "omurlararası disk", "c": "Anatomi", "x": "A herniated intervertebral disc can compress spinal nerves."},
    {"e": "jugular vein", "t": "şah damarı", "c": "Anatomi", "x": "The jugular veins carry deoxygenated blood from the head back to the heart."},
    {"e": "larynx", "t": "gırtlak", "c": "Anatomi", "x": "The larynx houses the vocal cords and produces sound."},
    {"e": "lymphatic system", "t": "lenf sistemi", "c": "Anatomi", "x": "The lymphatic system is a crucial part of the immune system."},
    {"e": "macrophage", "t": "makrofaj", "c": "Fizyoloji", "x": "Macrophages engulf and digest cellular debris and pathogens."},
    {"e": "mandible", "t": "alt çene kemiği", "c": "Anatomi", "x": "The mandible is the largest and strongest bone of the human face."},
    {"e": "maxilla", "t": "üst çene kemiği", "c": "Anatomi", "x": "The maxilla forms the upper jaw and the palate of the mouth."},
    {"e": "medulla oblongata", "t": "omurilik soğanı", "c": "Anatomi", "x": "The medulla oblongata controls autonomic functions like breathing."},
    {"e": "metabolism", "t": "metabolizma", "c": "Fizyoloji", "x": "Thyroid hormones regulate the body's basal metabolism."},
    {"e": "mucous membrane", "t": "mukoza", "c": "Anatomi", "x": "Mucous membranes line various cavities in the body and secrete mucus."},
    {"e": "myelin sheath", "t": "miyelin kılıf", "c": "Anatomi", "x": "Multiple sclerosis involves the destruction of the myelin sheath."},
    {"e": "myocardium", "t": "kalp kası tabakası", "c": "Anatomi", "x": "Myocarditis is an inflammation of the myocardium."},
    {"e": "neuron", "t": "sinir hücresi", "c": "Anatomi", "x": "Neurons transmit information to other nerve cells, muscle, or gland cells."},
    {"e": "olfactory nerve", "t": "koku siniri", "c": "Anatomi", "x": "Damage to the olfactory nerve can result in a loss of smell."},
    {"e": "optic nerve", "t": "görme siniri", "c": "Anatomi", "x": "The optic nerve transmits visual information from the retina to the brain."},
    {"e": "osteoblast", "t": "kemik yapan hücre", "c": "Fizyoloji", "x": "Osteoblasts are cells responsible for new bone formation."},
    {"e": "osteoclast", "t": "kemik yıkan hücre", "c": "Fizyoloji", "x": "Osteoclasts break down bone tissue during bone remodeling."},
    {"e": "pancreas", "t": "pankreas", "c": "Anatomi", "x": "The pancreas secretes digestive enzymes and hormones like insulin."},
    {"e": "patella", "t": "diz kapağı", "c": "Anatomi", "x": "The patella protects the anterior articular surface of the knee joint."},
    {"e": "pelvis", "t": "leğen kemiği", "c": "Anatomi", "x": "A fractured pelvis can cause significant internal bleeding."},
    {"e": "pericardium", "t": "kalp zarı", "c": "Anatomi", "x": "The pericardium is a double-walled sac containing the heart."},
    {"e": "peripheral nervous system", "t": "çevresel sinir sistemi", "c": "Anatomi", "x": "The peripheral nervous system connects the central nervous system to limbs."},
    {"e": "phagocytosis", "t": "fagositoz", "c": "Fizyoloji", "x": "Phagocytosis is a major mechanism used to remove pathogens."},
    {"e": "pharynx", "t": "yutak", "c": "Anatomi", "x": "The pharynx is part of both the digestive and respiratory systems."},
    {"e": "pineal gland", "t": "epifiz bezi", "c": "Anatomi", "x": "The pineal gland produces melatonin, which helps maintain circadian rhythm."},
    {"e": "pituitary gland", "t": "hipofiz bezi", "c": "Anatomi", "x": "The pituitary gland regulates growth, blood pressure, and reproduction."},
    {"e": "placenta", "t": "plasenta", "c": "Anatomi", "x": "The placenta provides oxygen and nutrients to the growing fetus."},
    {"e": "plasma", "t": "plazma", "c": "Anatomi", "x": "Plasma carries water, salts, and enzymes throughout the body."},
    {"e": "platelet", "t": "trombosit", "c": "Anatomi", "x": "Platelets clump together to form clots and stop bleeding."},
    {"e": "pulmonary artery", "t": "akciğer atardamarı", "c": "Anatomi", "x": "The pulmonary artery carries deoxygenated blood from the heart to the lungs."},
    {"e": "pulmonary vein", "t": "akciğer toplardamarı", "c": "Anatomi", "x": "The pulmonary veins transfer oxygenated blood from the lungs to the heart."},
    {"e": "red blood cell", "t": "alyuvar", "c": "Anatomi", "x": "Red blood cells are responsible for carrying oxygen to tissues."},
    {"e": "renal cortex", "t": "böbrek kabuğu", "c": "Anatomi", "x": "The renal cortex contains the nephrons, the functional units of the kidney."},
    {"e": "retina", "t": "ağ tabaka (retina)", "c": "Anatomi", "x": "The retina is the light-sensitive layer of tissue at the back of the inner eye."},
    {"e": "sacrum", "t": "sağrı kemiği", "c": "Anatomi", "x": "The sacrum is a large, triangular bone at the base of the spine."},
    {"e": "salivary gland", "t": "tükürük bezi", "c": "Anatomi", "x": "Salivary glands produce saliva, which begins the process of digestion."},
    {"e": "scapula", "t": "kürek kemiği", "c": "Anatomi", "x": "The scapula connects the humerus bone of the arm to the collarbone."},
    {"e": "sciatic nerve", "t": "siyatik siniri", "c": "Anatomi", "x": "The sciatic nerve is the longest and thickest nerve in the human body."},
    {"e": "sclera", "t": "göz akı", "c": "Anatomi", "x": "The sclera is the tough, white, outer layer of the eyeball."},
    {"e": "sebum", "t": "sebum (cilt yağı)", "c": "Fizyoloji", "x": "Sebum helps lubricate and waterproof the skin and hair."},
    {"e": "skeletal muscle", "t": "iskelet kası", "c": "Anatomi", "x": "Skeletal muscles are voluntary muscles attached to bones."},
    {"e": "smooth muscle", "t": "düz kas", "c": "Anatomi", "x": "Smooth muscle controls involuntary movements in organs like the stomach."},
    {"e": "spinal cord", "t": "omurilik", "c": "Anatomi", "x": "The spinal cord transmits neural signals between the brain and the rest of the body."},
    {"e": "spleen", "t": "dalak", "c": "Anatomi", "x": "The spleen filters blood as part of the immune system."},
    {"e": "sternum", "t": "göğüs kemiği", "c": "Anatomi", "x": "During open-heart surgery, the sternum is divided to access the heart."},
    {"e": "synapse", "t": "sinaps", "c": "Anatomi", "x": "A synapse is a structure that permits a neuron to pass an electrical signal."},
    {"e": "synovial fluid", "t": "eklem sıvısı", "c": "Anatomi", "x": "Synovial fluid reduces friction between the articular cartilage of synovial joints."},
    {"e": "tendon", "t": "tendon", "c": "Anatomi", "x": "An Achilles tendon rupture requires immediate medical evaluation."},
    {"e": "thalamus", "t": "talamus", "c": "Anatomi", "x": "The thalamus relays sensory and motor signals to the cerebral cortex."},
    {"e": "thoracic cavity", "t": "göğüs boşluğu", "c": "Anatomi", "x": "The thoracic cavity is protected by the thoracic wall (rib cage)."},
    {"e": "thymus", "t": "timüs bezi", "c": "Anatomi", "x": "The thymus serves a vital role in the training and development of T-lymphocytes."},
    {"e": "thyroid gland", "t": "tiroid bezi", "c": "Anatomi", "x": "An underactive thyroid gland can lead to weight gain and fatigue."},
    {"e": "trachea", "t": "soluk borusu", "c": "Anatomi", "x": "The trachea connects the larynx to the bronchi of the lungs."},
    {"e": "umbilical cord", "t": "göbek bağı", "c": "Anatomi", "x": "The umbilical cord supplies oxygen and nutrients to the developing embryo."},
    {"e": "ureter", "t": "üreter", "c": "Anatomi", "x": "Ureters are tubes made of smooth muscle fibers that propel urine from the kidneys."},
    {"e": "urethra", "t": "üretra", "c": "Anatomi", "x": "In males, the urethra travels through the penis and carries semen as well as urine."},
    {"e": "uterus", "t": "rahim", "c": "Anatomi", "x": "The uterus is a hollow muscular organ where a fetus develops."},
    {"e": "vagus nerve", "t": "vagus siniri", "c": "Anatomi", "x": "The vagus nerve regulates internal organ functions, such as digestion and heart rate."},
    {"e": "valve", "t": "kapakçık", "c": "Anatomi", "x": "Heart valves prevent the backward flow of blood."},
    {"e": "vein", "t": "toplardamar", "c": "Anatomi", "x": "Veins are blood vessels that carry blood towards the heart."},
    {"e": "vena cava", "t": "ana toplardamar", "c": "Anatomi", "x": "The superior vena cava returns deoxygenated blood from the upper half of the body."},
    {"e": "ventricle", "t": "karıncık", "c": "Anatomi", "x": "The left ventricle pumps oxygenated blood into the aorta."},
    {"e": "vertebra", "t": "omur", "c": "Anatomi", "x": "The human spine is made up of 33 vertebrae."},
    {"e": "vocal cords", "t": "ses telleri", "c": "Anatomi", "x": "Inflammation of the vocal cords can result in a loss of voice."},
    {"e": "white blood cell", "t": "akyuvar", "c": "Anatomi", "x": "A high white blood cell count often indicates an infection."},
    {"e": "zygote", "t": "zigot", "c": "Fizyoloji", "x": "A zygote is the initial cell formed when two gamete cells are joined."},
    
    // --- Pathologies & Diseases ---
    {"e": "abscess", "t": "apse", "c": "Hastalıklar", "x": "A dental abscess is a buildup of pus that forms inside the teeth or gums."},
    {"e": "acidosis", "t": "asidoz", "c": "Hastalıklar", "x": "Acidosis is a condition in which there is too much acid in the body fluids."},
    {"e": "aneurysm", "t": "anevrizma", "c": "Hastalıklar", "x": "A ruptured brain aneurysm is a life-threatening medical emergency."},
    {"e": "angina pectoris", "t": "kalp spazmı", "c": "Hastalıklar", "x": "Angina pectoris causes chest pain due to reduced blood flow to the heart."},
    {"e": "anorexia nervosa", "t": "anoreksiya", "c": "Hastalıklar", "x": "Anorexia nervosa is characterized by an abnormally low body weight."},
    {"e": "appendicitis", "t": "apandisit", "c": "Hastalıklar", "x": "Appendicitis typically presents with pain in the lower right abdomen."},
    {"e": "arrhythmia", "t": "aritmi", "c": "Hastalıklar", "x": "An arrhythmia can cause the heart to beat too fast, too slow, or irregularly."},
    {"e": "arteriosclerosis", "t": "damar sertliği", "c": "Hastalıklar", "x": "Arteriosclerosis restricts blood flow to your organs and tissues."},
    {"e": "arthritis", "t": "eklem iltihabı", "c": "Hastalıklar", "x": "Osteoarthritis is the most common form of arthritis."},
    {"e": "asthma", "t": "astım", "c": "Hastalıklar", "x": "Asthma attacks can be triggered by allergies, exercise, or cold air."},
    {"e": "atherosclerosis", "t": "damar tıkanıklığı", "c": "Hastalıklar", "x": "Atherosclerosis is a specific type of arteriosclerosis involving plaque buildup."},
    {"e": "atrophy", "t": "körelme", "c": "Hastalıklar", "x": "Muscle atrophy can occur after prolonged bed rest or immobilization."},
    {"e": "autoimmune disease", "t": "otoimmün hastalık", "c": "Hastalıklar", "x": "In an autoimmune disease, the immune system attacks healthy cells."},
    {"e": "benign tumor", "t": "iyi huylu tümör", "c": "Hastalıklar", "x": "A benign tumor does not spread to other parts of the body."},
    {"e": "bipolar disorder", "t": "bipolar bozukluk", "c": "Hastalıklar", "x": "Bipolar disorder causes extreme mood swings."},
    {"e": "bronchitis", "t": "bronşit", "c": "Hastalıklar", "x": "Acute bronchitis is usually caused by a viral infection."},
    {"e": "bulimia nervosa", "t": "bulimiya", "c": "Hastalıklar", "x": "Bulimia nervosa is an eating disorder characterized by bingeing and purging."},
    {"e": "carcinoma", "t": "karsinom", "c": "Hastalıklar", "x": "Basal cell carcinoma is the most common form of skin cancer."},
    {"e": "cataract", "t": "katarakt", "c": "Hastalıklar", "x": "A cataract is a clouding of the normally clear lens of the eye."},
    {"e": "cerebral palsy", "t": "serebral palsi", "c": "Hastalıklar", "x": "Cerebral palsy is a group of disorders that affect a person's ability to move."},
    {"e": "cirrhosis", "t": "siroz", "c": "Hastalıklar", "x": "Chronic alcohol abuse and hepatitis are leading causes of liver cirrhosis."},
    {"e": "concussion", "t": "beyin sarsıntısı", "c": "Hastalıklar", "x": "A concussion is a traumatic brain injury that affects brain function."},
    {"e": "congenital heart defect", "t": "doğumsal kalp kusuru", "c": "Hastalıklar", "x": "A congenital heart defect is a problem with the structure of the heart present at birth."},
    {"e": "conjunctivitis", "t": "göz nezlesi", "c": "Hastalıklar", "x": "Conjunctivitis, or pink eye, is highly contagious."},
    {"e": "cystic fibrosis", "t": "kistik fibrozis", "c": "Hastalıklar", "x": "Cystic fibrosis causes the body to produce thick, sticky mucus."},
    {"e": "dementia", "t": "demans", "c": "Hastalıklar", "x": "Alzheimer's disease is the most common cause of dementia."},
    {"e": "diabetes mellitus", "t": "şeker hastalığı", "c": "Hastalıklar", "x": "Type 2 diabetes mellitus is closely linked to obesity and a sedentary lifestyle."},
    {"e": "diphtheria", "t": "difteri", "c": "Hastalıklar", "x": "Diphtheria is a serious bacterial infection usually affecting the mucous membranes."},
    {"e": "dysentery", "t": "dizanteri", "c": "Hastalıklar", "x": "Dysentery causes severe diarrhea with blood and mucus in the feces."},
    {"e": "dyslexia", "t": "disleksi", "c": "Hastalıklar", "x": "Dyslexia is a learning disorder that involves difficulty reading."},
    {"e": "ectopic pregnancy", "t": "dış gebelik", "c": "Hastalıklar", "x": "An ectopic pregnancy occurs when a fertilized egg implants outside the uterus."},
    {"e": "edema", "t": "ödem", "c": "Hastalıklar", "x": "Pulmonary edema is a condition caused by excess fluid in the lungs."},
    {"e": "embolism", "t": "emboli", "c": "Hastalıklar", "x": "A pulmonary embolism occurs when a blood clot blocks an artery in the lungs."},
    {"e": "emphysema", "t": "amfizem", "c": "Hastalıklar", "x": "Smoking is the leading cause of emphysema."},
    {"e": "encephalitis", "t": "beyin iltihabı", "c": "Hastalıklar", "x": "Encephalitis is an inflammation of the active tissues of the brain."},
    {"e": "endometriosis", "t": "endometriyozis", "c": "Hastalıklar", "x": "Endometriosis can cause significant pelvic pain and infertility."},
    {"e": "epilepsy", "t": "epilepsi", "c": "Hastalıklar", "x": "Epilepsy is a central nervous system disorder in which brain activity becomes abnormal."},
    {"e": "fibromyalgia", "t": "fibromiyalji", "c": "Hastalıklar", "x": "Fibromyalgia is characterized by widespread musculoskeletal pain."},
    {"e": "gangrene", "t": "kangren", "c": "Hastalıklar", "x": "Gangrene occurs when body tissue dies due to a loss of blood supply."},
    {"e": "gastritis", "t": "gastrit", "c": "Hastalıklar", "x": "Helicobacter pylori infection is a common cause of chronic gastritis."},
    {"e": "gastroenteritis", "t": "mide-bağırsak iltihabı", "c": "Hastalıklar", "x": "Gastroenteritis, or stomach flu, is an inflammation of the lining of the intestines."},
    {"e": "glaucoma", "t": "göz tansiyonu", "c": "Hastalıklar", "x": "Glaucoma is a group of eye conditions that damage the optic nerve."},
    {"e": "goiter", "t": "guatr", "c": "Hastalıklar", "x": "An iodine deficiency is the most common cause of goiter worldwide."},
    {"e": "gout", "t": "gut hastalığı", "c": "Hastalıklar", "x": "Gout is a complex form of arthritis characterized by severe pain in the joints."},
    {"e": "hemophilia", "t": "hemofili", "c": "Hastalıklar", "x": "Hemophilia is a rare disorder in which your blood doesn't clot normally."},
    {"e": "hemorrhage", "t": "kanama", "c": "Hastalıklar", "x": "A cerebral hemorrhage can cause significant brain damage."},
    {"e": "hemorrhoids", "t": "basur", "c": "Hastalıklar", "x": "Hemorrhoids are swollen veins in your lower rectum."},
    {"e": "hepatitis", "t": "hepatit", "c": "Hastalıklar", "x": "Hepatitis C is usually transmitted through exposure to infected blood."},
    {"e": "hernia", "t": "fıtık", "c": "Hastalıklar", "x": "An inguinal hernia occurs when tissue pushes through a weak spot in your groin muscle."},
    {"e": "herpes", "t": "uçuk", "c": "Hastalıklar", "x": "The herpes simplex virus can cause both oral and genital herpes."},
    {"e": "Hodgkin's lymphoma", "t": "Hodgkin lenfoma", "c": "Hastalıklar", "x": "Hodgkin's lymphoma is a type of cancer that affects the lymphatic system."},
    {"e": "hypertension", "t": "hipertansiyon", "c": "Hastalıklar", "x": "Untreated hypertension increases the risk of heart attack and stroke."},
    {"e": "hyperthyroidism", "t": "hipertiroidi", "c": "Hastalıklar", "x": "Hyperthyroidism occurs when your thyroid gland produces too much thyroxine."},
    {"e": "hypoglycemia", "t": "hipoglisemi", "c": "Hastalıklar", "x": "Hypoglycemia is common in people with diabetes who take too much insulin."},
    {"e": "hypothyroidism", "t": "hipotiroidi", "c": "Hastalıklar", "x": "Hypothyroidism can cause fatigue, weight gain, and depression."},
    {"e": "ischemia", "t": "iskemi", "c": "Hastalıklar", "x": "Myocardial ischemia occurs when blood flow to your heart is reduced."},
    {"e": "jaundice", "t": "sarılık", "c": "Hastalıklar", "x": "Jaundice is often a sign of a problem with the liver, gallbladder, or pancreas."},
    {"e": "leukemia", "t": "lösemi", "c": "Hastalıklar", "x": "Leukemia usually involves the white blood cells."},
    {"e": "lupus", "t": "lupus", "c": "Hastalıklar", "x": "Lupus is a systemic autoimmune disease that occurs when your body's immune system attacks your own tissues."},
    {"e": "Lyme disease", "t": "Lyme hastalığı", "c": "Hastalıklar", "x": "Lyme disease is transmitted through the bite of infected ticks."},
    {"e": "lymphoma", "t": "lenf bezi kanseri", "c": "Hastalıklar", "x": "Lymphoma begins in infection-fighting cells of the immune system."},
    {"e": "malaria", "t": "sıtma", "c": "Hastalıklar", "x": "Malaria is caused by a parasite that commonly infects a certain type of mosquito."},
    {"e": "malignant tumor", "t": "kötü huylu tümör", "c": "Hastalıklar", "x": "A malignant tumor can grow rapidly and spread to other tissues."},
    {"e": "measles", "t": "kızamık", "c": "Hastalıklar", "x": "Measles is a highly contagious infectious disease caused by the measles virus."},
    {"e": "melanoma", "t": "melanom", "c": "Hastalıklar", "x": "Melanoma is the most serious type of skin cancer."},
    {"e": "meningitis", "t": "menenjit", "c": "Hastalıklar", "x": "Viral meningitis is usually mild and often clears on its own."},
    {"e": "metastasis", "t": "metastaz", "c": "Hastalıklar", "x": "Bone metastasis occurs when cancer cells spread from their original site to a bone."},
    {"e": "multiple sclerosis (MS)", "t": "Multipl Skleroz (MS)", "c": "Hastalıklar", "x": "Multiple sclerosis is a potentially disabling disease of the brain and spinal cord."},
    {"e": "mumps", "t": "kabakulak", "c": "Hastalıklar", "x": "Mumps is best known for the puffy cheeks and tender, swollen jaw that it causes."},
    {"e": "muscular dystrophy", "t": "kas erimesi hastalığı", "c": "Hastalıklar", "x": "Muscular dystrophy is a group of diseases that cause progressive weakness and loss of muscle mass."},
    {"e": "myocardial infarction", "t": "kalp krizi", "c": "Hastalıklar", "x": "A myocardial infarction occurs when blood flow to the heart muscle is abruptly cut off."},
    {"e": "necrosis", "t": "nekroz", "c": "Hastalıklar", "x": "Avascular necrosis is the death of bone tissue due to a lack of blood supply."},
    {"e": "neoplasm", "t": "neoplazm", "c": "Hastalıklar", "x": "A neoplasm is an abnormal growth of tissue that can be benign or malignant."},
    {"e": "nephritis", "t": "böbrek iltihabı", "c": "Hastalıklar", "x": "Lupus nephritis is an inflammation of the kidneys caused by systemic lupus erythematosus."},
    {"e": "neuropathy", "t": "nöropati", "c": "Hastalıklar", "x": "Peripheral neuropathy is a result of damage to the peripheral nerves."},
    {"e": "obesity", "t": "obezite", "c": "Hastalıklar", "x": "Childhood obesity is a serious medical condition that affects children and adolescents."},
    {"e": "osteoarthritis", "t": "kireçlenme", "c": "Hastalıklar", "x": "Osteoarthritis is the most common form of arthritis, affecting millions of people worldwide."},
    {"e": "osteoporosis", "t": "kemik erimesi", "c": "Hastalıklar", "x": "Osteoporosis causes bones to become weak and brittle."},
    {"e": "otitis media", "t": "orta kulak iltihabı", "c": "Hastalıklar", "x": "Otitis media is very common in young children."},
    {"e": "pancreatitis", "t": "pankreas iltihabı", "c": "Hastalıklar", "x": "Acute pancreatitis can be a life-threatening illness."},
    {"e": "paralysis", "t": "felç", "c": "Hastalıklar", "x": "A spinal cord injury can result in permanent paralysis."},
    {"e": "Parkinson's disease", "t": "Parkinson hastalığı", "c": "Hastalıklar", "x": "Parkinson's disease is a progressive nervous system disorder that affects movement."},
    {"e": "peptic ulcer", "t": "mide ülseri", "c": "Hastalıklar", "x": "Stress and spicy foods do not cause peptic ulcers, but can make symptoms worse."},
    {"e": "pertussis", "t": "boğmaca", "c": "Hastalıklar", "x": "Pertussis is a highly contagious respiratory tract infection."},
    {"e": "phlebitis", "t": "toplardamar iltihabı", "c": "Hastalıklar", "x": "Phlebitis often occurs in conjunction with thrombosis."},
    {"e": "pneumonia", "t": "zatürre", "c": "Hastalıklar", "x": "Pneumonia is an infection that inflames the air sacs in one or both lungs."},
    {"e": "poliomyelitis", "t": "çocuk felci", "c": "Hastalıklar", "x": "Polio is a disabling and life-threatening disease caused by the poliovirus."},
    {"e": "psoriasis", "t": "sedef hastalığı", "c": "Hastalıklar", "x": "Psoriasis is a skin disease that causes red, itchy scaly patches."},
    {"e": "rabies", "t": "kuduz", "c": "Hastalıklar", "x": "Rabies is a deadly virus spread to people from the saliva of infected animals."},
    {"e": "rheumatoid arthritis", "t": "romatoid artrit", "c": "Hastalıklar", "x": "Rheumatoid arthritis is a chronic inflammatory disorder affecting many joints."},
    {"e": "rubella", "t": "kızamıkçık", "c": "Hastalıklar", "x": "Rubella can cause severe congenital defects if a woman is infected during pregnancy."},
    {"e": "schizophrenia", "t": "şizofreni", "c": "Hastalıklar", "x": "Schizophrenia is a severe mental disorder in which people interpret reality abnormally."},
    {"e": "scoliosis", "t": "skolyoz", "c": "Hastalıklar", "x": "Scoliosis is a sideways curvature of the spine that occurs most often during the growth spurt just before puberty."},
    {"e": "scurvy", "t": "iskorbüt", "c": "Hastalıklar", "x": "Scurvy is a disease resulting from a lack of vitamin C."},
    {"e": "sepsis", "t": "kan zehirlenmesi", "c": "Hastalıklar", "x": "Sepsis is a potentially life-threatening condition caused by the body's response to an infection."},
    {"e": "shingles", "t": "zona", "c": "Hastalıklar", "x": "Shingles is a viral infection that causes a painful rash."},
    {"e": "sleep apnea", "t": "uyku apnesi", "c": "Hastalıklar", "x": "Sleep apnea is a potentially serious sleep disorder in which breathing repeatedly stops and starts."},
    {"e": "spina bifida", "t": "ayrık omurga hastalığı", "c": "Hastalıklar", "x": "Spina bifida is a birth defect that occurs when the spine and spinal cord don't form properly."},
    {"e": "stroke", "t": "inme", "c": "Hastalıklar", "x": "An ischemic stroke happens when the blood supply to part of the brain is interrupted."},
    {"e": "syphilis", "t": "frengi", "c": "Hastalıklar", "x": "Syphilis is a bacterial infection usually spread by sexual contact."},
    {"e": "tetanus", "t": "tetanoz", "c": "Hastalıklar", "x": "Tetanus is a serious bacterial infection that causes painful muscle spasms."},
    {"e": "thrombosis", "t": "tromboz", "c": "Hastalıklar", "x": "Deep vein thrombosis (DVT) occurs when a blood clot forms in a deep vein in your body."},
    {"e": "tonsillitis", "t": "bademcik iltihabı", "c": "Hastalıklar", "x": "Tonsillitis is an inflammation of the tonsils, two oval-shaped pads of tissue at the back of the throat."},
    {"e": "tuberculosis", "t": "verem", "c": "Hastalıklar", "x": "Tuberculosis is a potentially serious infectious bacterial disease that mainly affects the lungs."},
    {"e": "typhoid fever", "t": "tifo", "c": "Hastalıklar", "x": "Typhoid fever is a life-threatening infection caused by the bacterium Salmonella Typhi."},
    {"e": "ulcerative colitis", "t": "ülseratif kolit", "c": "Hastalıklar", "x": "Ulcerative colitis is an inflammatory bowel disease (IBD) that causes long-lasting inflammation."},
    {"e": "varicose veins", "t": "varis", "c": "Hastalıklar", "x": "Varicose veins are twisted, enlarged veins, most commonly appearing in the legs."},
    {"e": "vertigo", "t": "baş dönmesi", "c": "Hastalıklar", "x": "Vertigo is a sensation of feeling off balance, often caused by an inner ear problem."},
    {"e": "yellow fever", "t": "sarı humma", "c": "Hastalıklar", "x": "Yellow fever is an acute viral hemorrhagic disease transmitted by infected mosquitoes."},
    {"e": "Zika virus", "t": "Zika virüsü hastalığı", "c": "Hastalıklar", "x": "Zika virus infection during pregnancy can cause a birth defect of the brain called microcephaly."},

    // --- Diagnostics, Symptoms & Signs ---
    {"e": "abnormal", "t": "anormal", "c": "Tanı & Teşhis", "x": "An abnormal heart rhythm was detected during the ECG."},
    {"e": "acute", "t": "akut", "c": "Tanı & Teşhis", "x": "The patient presented with acute abdominal pain."},
    {"e": "amnesia", "t": "hafıza kaybı", "c": "Tanı & Teşhis", "x": "Retrograde amnesia is the inability to retrieve information that was acquired before a particular date."},
    {"e": "analgesia", "t": "ağrı yitimi", "c": "Tanı & Teşhis", "x": "Epidural analgesia provides excellent pain relief during labor."},
    {"e": "anaphylaxis", "t": "anafilaksi", "c": "Tanı & Teşhis", "x": "Anaphylaxis is a severe, potentially life-threatening allergic reaction."},
    {"e": "anorexia", "t": "iştahsızlık", "c": "Tanı & Teşhis", "x": "Anorexia can be a symptom of many underlying medical conditions, including cancer."},
    {"e": "antigen", "t": "antijen", "c": "Tanı & Teşhis", "x": "The rapid antigen test can provide results in about 15 minutes."},
    {"e": "aphasia", "t": "afazi", "c": "Tanı & Teşhis", "x": "Aphasia is a condition that robs you of the ability to communicate, often after a stroke."},
    {"e": "asymptomatic", "t": "semptomsuz", "c": "Tanı & Teşhis", "x": "Many people infected with the virus remain completely asymptomatic."},
    {"e": "auscultation", "t": "dinleme", "c": "Tanı & Teşhis", "x": "Auscultation of the lungs revealed a crackling sound, suggesting pneumonia."},
    {"e": "benign", "t": "iyi huylu", "c": "Tanı & Teşhis", "x": "The biopsy confirmed that the breast lump was benign."},
    {"e": "biopsy", "t": "biyopsi", "c": "Tanı & Teşhis", "x": "A liver biopsy is a procedure to remove a small piece of liver tissue."},
    {"e": "blood pressure", "t": "tansiyon", "c": "Tanı & Teşhis", "x": "A sphygmomanometer is a device used to measure blood pressure."},
    {"e": "bradycardia", "t": "nabız yavaşlığı", "c": "Tanı & Teşhis", "x": "Bradycardia is a slower than normal heart rate."},
    {"e": "carcinogen", "t": "kanserojen", "c": "Tanı & Teşhis", "x": "Asbestos is a known carcinogen that causes mesothelioma."},
    {"e": "cardiac arrest", "t": "kalp durması", "c": "Tanı & Teşhis", "x": "Sudden cardiac arrest is the abrupt loss of heart function."},
    {"e": "chronic", "t": "kronik", "c": "Tanı & Teşhis", "x": "Chronic kidney disease is the gradual loss of kidney function."},
    {"e": "cognitive", "t": "bilişsel", "c": "Tanı & Teşhis", "x": "The Mini-Mental State Examination is used to assess cognitive impairment."},
    {"e": "complication", "t": "komplikasyon", "c": "Tanı & Teşhis", "x": "Infection is a common complication of surgery."},
    {"e": "computed tomography (CT)", "t": "bilgisayarlı tomografi", "c": "Tanı & Teşhis", "x": "A CT scan can show detailed images of any part of the body."},
    {"e": "cyanosis", "t": "morarma", "c": "Tanı & Teşhis", "x": "Cyanosis is a bluish discoloration of the skin resulting from poor circulation or inadequate oxygenation."},
    {"e": "diagnosis", "t": "teşhis", "c": "Tanı & Teşhis", "x": "Early diagnosis is key to successfully treating many forms of cancer."},
    {"e": "diarrhea", "t": "ishal", "c": "Tanı & Teşhis", "x": "Chronic diarrhea can lead to severe dehydration and electrolyte imbalance."},
    {"e": "dilatation", "t": "genişleme", "c": "Tanı & Teşhis", "x": "Pupillary dilatation can occur as a side effect of certain medications."},
    {"e": "dyspnea", "t": "nefes darlığı", "c": "Tanı & Teşhis", "x": "Dyspnea is a common symptom of heart and lung conditions."},
    {"e": "echocardiogram", "t": "ekokardiyografi", "c": "Tanı & Teşhis", "x": "An echocardiogram uses sound waves to produce images of your heart."},
    {"e": "electrocardiogram (ECG)", "t": "elektrokardiyografi", "c": "Tanı & Teşhis", "x": "An ECG is a simple, painless test that measures your heart's electrical activity."},
    {"e": "electroencephalogram (EEG)", "t": "elektroensefalografi", "c": "Tanı & Teşhis", "x": "An EEG is used to detect abnormalities in brain waves, often diagnosing epilepsy."},
    {"e": "endemic", "t": "endemik", "c": "Tanı & Teşhis", "x": "Malaria is endemic in many parts of Africa and Asia."},
    {"e": "endoscope", "t": "endoskop", "c": "Tanı & Teşhis", "x": "An endoscope is a long, thin, flexible tube that has a light and camera at one end."},
    {"e": "epidemic", "t": "epidemi", "c": "Tanı & Teşhis", "x": "The flu epidemic caused hospitals to reach full capacity."},
    {"e": "erythema", "t": "kızarıklık", "c": "Tanı & Teşhis", "x": "Erythema is redness of the skin, either in a limited area or all over."},
    {"e": "etiology", "t": "etiyoloji", "c": "Tanı & Teşhis", "x": "The etiology of autoimmune diseases is not entirely understood."},
    {"e": "exacerbation", "t": "alevlenme", "c": "Tanı & Teşhis", "x": "An asthma exacerbation, or asthma attack, is a sudden worsening of asthma symptoms."},
    {"e": "fatigue", "t": "yorgunluk", "c": "Tanı & Teşhis", "x": "Chronic fatigue syndrome is a complicated disorder characterized by extreme fatigue."},
    {"e": "fever", "t": "ateş", "c": "Tanı & Teşhis", "x": "A high fever in a young infant is a reason to seek immediate medical attention."},
    {"e": "fracture", "t": "kırık", "c": "Tanı & Teşhis", "x": "An X-ray was taken to determine if the bone had a fracture."},
    {"e": "hematoma", "t": "hematom", "c": "Tanı & Teşhis", "x": "A subdural hematoma is a collection of blood outside the brain."},
    {"e": "hypotension", "t": "düşük tansiyon", "c": "Tanı & Teşhis", "x": "Orthostatic hypotension is a form of low blood pressure that happens when you stand up from sitting or lying down."},
    {"e": "hypoxia", "t": "hipoksi", "c": "Tanı & Teşhis", "x": "Hypoxia is a state in which oxygen is not available in sufficient amounts at the tissue level."},
    {"e": "idiopathic", "t": "nedeni bilinmeyen", "c": "Tanı & Teşhis", "x": "Idiopathic pulmonary fibrosis is a disease that causes scarring of the lungs with an unknown cause."},
    {"e": "immunity", "t": "bağışıklık", "c": "Tanı & Teşhis", "x": "Vaccines help develop immunity by imitating an infection."},
    {"e": "incidence", "t": "görülme sıklığı", "c": "Tanı & Teşhis", "x": "The incidence of type 2 diabetes is increasing globally."},
    {"e": "incubation period", "t": "kuluçka dönemi", "c": "Tanı & Teşhis", "x": "The incubation period for COVID-19 can range from 1 to 14 days."},
    {"e": "infarction", "t": "enfarktüs", "c": "Tanı & Teşhis", "x": "Myocardial infarction is the medical term for a heart attack."},
    {"e": "infection", "t": "enfeksiyon", "c": "Tanı & Teşhis", "x": "A urinary tract infection is an infection in any part of your urinary system."},
    {"e": "inflammation", "t": "enflamasyon", "c": "Tanı & Teşhis", "x": "Inflammation is a vital part of the immune system's response to injury and infection."},
    {"e": "insomnia", "t": "uykusuzluk", "c": "Tanı & Teşhis", "x": "Insomnia can sap not only your energy level and mood but also your health."},
    {"e": "lesion", "t": "lezyon", "c": "Tanı & Teşhis", "x": "A skin lesion is a part of the skin that has an abnormal growth or appearance."},
    {"e": "lethargy", "t": "uyuşukluk", "c": "Tanı & Teşhis", "x": "The patient complained of profound lethargy and inability to concentrate."},
    {"e": "magnetic resonance imaging (MRI)", "t": "manyetik rezonans görüntüleme", "c": "Tanı & Teşhis", "x": "An MRI scan uses a strong magnetic field and radio waves to create detailed images of the organs."},
    {"e": "malignant", "t": "habis", "c": "Tanı & Teşhis", "x": "Malignant tumors are cancerous and can invade nearby tissues."},
    {"e": "morbidity", "t": "hastalanma oranı", "c": "Tanı & Teşhis", "x": "Morbidity rate is the frequency or proportion with which a disease appears in a population."},
    {"e": "mortality", "t": "ölüm oranı", "c": "Tanı & Teşhis", "x": "Infant mortality is the death of young children under the age of one."},
    {"e": "nausea", "t": "mide bulantısı", "c": "Tanı & Teşhis", "x": "Nausea and vomiting are common side effects of chemotherapy."},
    {"e": "nosocomial", "t": "hastane kaynaklı", "c": "Tanı & Teşhis", "x": "A nosocomial infection is contracted because of an infection or toxin that exists in a certain location, such as a hospital."},
    {"e": "pallor", "t": "solgunluk", "c": "Tanı & Teşhis", "x": "Pallor is a pale color of the skin that can be caused by illness, emotional shock, or stress."},
    {"e": "palpitation", "t": "çarpıntı", "c": "Tanı & Teşhis", "x": "Heart palpitations are feelings of having a fast-beating, fluttering, or pounding heart."},
    {"e": "pandemic", "t": "pandemi", "c": "Tanı & Teşhis", "x": "The WHO declared the COVID-19 outbreak a global pandemic."},
    {"e": "pathogen", "t": "patojen", "c": "Tanı & Teşhis", "x": "A pathogen is an organism that causes disease."},
    {"e": "pathology", "t": "patoloji", "c": "Tanı & Teşhis", "x": "Pathology is the study of the causes and effects of disease or injury."},
    {"e": "phlegm", "t": "balgam", "c": "Tanı & Teşhis", "x": "Phlegm is a type of mucus produced in the lungs and lower respiratory tract."},
    {"e": "prevalence", "t": "yaygınlık", "c": "Tanı & Teşhis", "x": "The prevalence of obesity among adults in the US is high."},
    {"e": "prognosis", "t": "prognoz", "c": "Tanı & Teşhis", "x": "The prognosis for patients with early-stage breast cancer is excellent."},
    {"e": "prophylaxis", "t": "profilaksi", "c": "Tanı & Teşhis", "x": "Dental prophylaxis is a cleaning procedure performed to thoroughly clean the teeth."},
    {"e": "rash", "t": "döküntü", "c": "Tanı & Teşhis", "x": "A rash is a noticeable change in the texture or color of your skin."},
    {"e": "relapse", "t": "nüksetme", "c": "Tanı & Teşhis", "x": "The patient experienced a relapse of leukemia after two years of remission."},
    {"e": "remission", "t": "remisyon", "c": "Tanı & Teşhis", "x": "When the cancer is in remission, it means that the signs and symptoms of your cancer are reduced."},
    {"e": "seizure", "t": "nöbet", "c": "Tanı & Teşhis", "x": "A seizure is a sudden, uncontrolled electrical disturbance in the brain."},
    {"e": "spasm", "t": "spazm", "c": "Tanı & Teşhis", "x": "A muscle spasm is a sudden, involuntary movement in one or more muscles."},
    {"e": "sputum", "t": "balgam", "c": "Tanı & Teşhis", "x": "A sputum culture is a test to check for bacteria or another type of organism that may be causing an infection."},
    {"e": "symptom", "t": "belirti", "c": "Tanı & Teşhis", "x": "Fever and cough are common symptoms of respiratory infections."},
    {"e": "syndrome", "t": "sendrom", "c": "Tanı & Teşhis", "x": "Down syndrome is a genetic condition caused by a full or partial extra copy of chromosome 21."},
    {"e": "tachycardia", "t": "taşikardi", "c": "Tanı & Teşhis", "x": "Tachycardia is a heart rate that's too fast."},
    {"e": "triage", "t": "triyaj", "c": "Tanı & Teşhis", "x": "The triage nurse assesses patients to determine the urgency of their condition."},
    {"e": "tumor", "t": "tümör", "c": "Tanı & Teşhis", "x": "A brain tumor is a mass or growth of abnormal cells in your brain."},
    {"e": "ulcer", "t": "ülser", "c": "Tanı & Teşhis", "x": "A peptic ulcer is a sore on the lining of your stomach, small intestine or esophagus."},

    // --- Treatments, Medications & Procedures ---
    {"e": "acupuncture", "t": "akupunktur", "c": "Tedavi & İlaç", "x": "Acupuncture involves inserting very thin needles through your skin at strategic points on your body."},
    {"e": "adjuvant therapy", "t": "adjuvan tedavi", "c": "Tedavi & İlaç", "x": "Adjuvant therapy is given in addition to the primary, main, or initial treatment."},
    {"e": "amputation", "t": "amputasyon", "c": "Tedavi & İlaç", "x": "Amputation is the removal of a limb by trauma, medical illness, or surgery."},
    {"e": "analgesic", "t": "ağrı kesici", "c": "Tedavi & İlaç", "x": "Analgesics are medicines that are used to relieve pain."},
    {"e": "anesthesia", "t": "anestezi", "c": "Tedavi & İlaç", "x": "General anesthesia puts you to sleep so you don't feel pain during surgery."},
    {"e": "angioplasty", "t": "anjiyoplasti", "c": "Tedavi & İlaç", "x": "Angioplasty is a procedure used to open clogged heart arteries."},
    {"e": "antacid", "t": "mide asidini giderici", "c": "Tedavi & İlaç", "x": "Antacids help treat heartburn by neutralizing stomach acid."},
    {"e": "antibiotic", "t": "antibiyotik", "c": "Tedavi & İlaç", "x": "Antibiotics are medicines that fight bacterial infections in people and animals."},
    {"e": "antibody", "t": "antikor", "c": "Tedavi & İlaç", "x": "Monoclonal antibodies are laboratory-produced molecules engineered to serve as substitute antibodies."},
    {"e": "anticoagulant", "t": "kan sulandırıcı", "c": "Tedavi & İlaç", "x": "Anticoagulants are medicines that help prevent blood clots."},
    {"e": "antidepressant", "t": "antidepresan", "c": "Tedavi & İlaç", "x": "Antidepressants are medications prescribed to treat clinical depression."},
    {"e": "antidote", "t": "panzehir", "c": "Tedavi & İlaç", "x": "An antidote is a medicine that counteracts a specific poison."},
    {"e": "antiemetic", "t": "bulantı önleyici", "c": "Tedavi & İlaç", "x": "Antiemetics are drugs that are effective against vomiting and nausea."},
    {"e": "antifungal", "t": "mantar ilacı", "c": "Tedavi & İlaç", "x": "Antifungal medicines are used to treat fungal infections."},
    {"e": "antihistamine", "t": "antihistaminik", "c": "Tedavi & İlaç", "x": "Antihistamines are commonly used to treat symptoms of allergies."},
    {"e": "anti-inflammatory", "t": "iltihap önleyici", "c": "Tedavi & İlaç", "x": "Nonsteroidal anti-inflammatory drugs (NSAIDs) reduce pain and inflammation."},
    {"e": "antipyretic", "t": "ateş düşürücü", "c": "Tedavi & İlaç", "x": "Acetaminophen is a common antipyretic used to reduce fever."},
    {"e": "antiseptic", "t": "antiseptik", "c": "Tedavi & İlaç", "x": "Antiseptics are applied to living tissue/skin to reduce the possibility of infection."},
    {"e": "antiviral", "t": "antiviral", "c": "Tedavi & İlaç", "x": "Antiviral drugs are a class of medication used specifically for treating viral infections."},
    {"e": "arthroscopy", "t": "artroskopi", "c": "Tedavi & İlaç", "x": "Arthroscopy is a procedure for diagnosing and treating joint problems."},
    {"e": "aspirator", "t": "aspiratör", "c": "Tedavi & İlaç", "x": "A surgical aspirator is used to remove blood and fluids from a surgical site."},
    {"e": "bandage", "t": "bandaj", "c": "Tedavi & İlaç", "x": "Apply a sterile bandage to the wound to keep it clean."},
    {"e": "bariatric surgery", "t": "obezite cerrahisi", "c": "Tedavi & İlaç", "x": "Bariatric surgery is a weight-loss surgery for people who are severely obese."},
    {"e": "blood transfusion", "t": "kan nakli", "c": "Tedavi & İlaç", "x": "A blood transfusion is a routine medical procedure in which donated blood is provided to you."},
    {"e": "bone marrow transplant", "t": "kemik iliği nakli", "c": "Tedavi & İlaç", "x": "A bone marrow transplant is a procedure to replace damaged or destroyed bone marrow."},
    {"e": "bronchodilator", "t": "bronkodilatör", "c": "Tedavi & İlaç", "x": "Bronchodilators make breathing easier by relaxing the muscles in the lungs."},
    {"e": "bypass surgery", "t": "bypass ameliyatı", "c": "Tedavi & İlaç", "x": "Coronary artery bypass surgery creates a new path for blood to flow to the heart."},
    {"e": "capsule", "t": "kapsül", "c": "Tedavi & İlaç", "x": "The medication is available in tablet or capsule form."},
    {"e": "catheter", "t": "sonda", "c": "Tedavi & İlaç", "x": "A urinary catheter is a flexible tube used to empty the bladder and collect urine."},
    {"e": "chemotherapy", "t": "kemoterapi", "c": "Tedavi & İlaç", "x": "Chemotherapy uses powerful chemicals to kill fast-growing cells in your body."},
    {"e": "chiropractic", "t": "kiropraktik", "c": "Tedavi & İlaç", "x": "Chiropractic care focuses on diagnosing and treating neuromuscular disorders."},
    {"e": "colonoscopy", "t": "kolonoskopi", "c": "Tedavi & İlaç", "x": "A colonoscopy is an exam used to detect changes or abnormalities in the large intestine."},
    {"e": "corticosteroid", "t": "kortikosteroid", "c": "Tedavi & İlaç", "x": "Corticosteroids are used to provide relief for inflamed areas of the body."},
    {"e": "CPR", "t": "kalp masajı (CPR)", "c": "Tedavi & İlaç", "x": "CPR is an emergency procedure that can help save a person's life if their breathing or heart stops."},
    {"e": "defibrillator", "t": "kalp şok cihazı", "c": "Tedavi & İlaç", "x": "An automated external defibrillator (AED) can restore a normal heartbeat."},
    {"e": "dialysis", "t": "diyaliz", "c": "Tedavi & İlaç", "x": "Dialysis is a treatment that does some of the things done by healthy kidneys."},
    {"e": "diuretic", "t": "idrar söktürücü", "c": "Tedavi & İlaç", "x": "Diuretics, sometimes called water pills, help rid your body of salt and water."},
    {"e": "dosage", "t": "doz", "c": "Tedavi & İlaç", "x": "Do not exceed the recommended dosage of this medication."},
    {"e": "echocardiography", "t": "ekokardiyografi", "c": "Tedavi & İlaç", "x": "Echocardiography uses standard ultrasound to create images of the heart."},
    {"e": "electroconvulsive therapy", "t": "elektroşok tedavisi", "c": "Tedavi & İlaç", "x": "ECT is a psychiatric treatment in which seizures are electrically induced in patients to provide relief from mental disorders."},
    {"e": "endoscopy", "t": "endoskopi", "c": "Tedavi & İlaç", "x": "Endoscopy is a procedure used in medicine to look inside the body."},
    {"e": "epidural", "t": "epidural anestezi", "c": "Tedavi & İlaç", "x": "An epidural is a method of delivering anesthesia to stop pain during childbirth."},
    {"e": "excision", "t": "eksizyon", "c": "Tedavi & İlaç", "x": "Surgical excision is the removal of tissue using a scalpel or other cutting instrument."},
    {"e": "gastric bypass", "t": "mide bypass'ı", "c": "Tedavi & İlaç", "x": "Gastric bypass is a type of weight-loss surgery that involves creating a small pouch from the stomach."},
    {"e": "graft", "t": "greft", "c": "Tedavi & İlaç", "x": "A skin graft is a surgical procedure that involves removing skin from one area of the body and moving it to another."},
    {"e": "homeopathy", "t": "homeopati", "c": "Tedavi & İlaç", "x": "Homeopathy is a medical system based on the belief that the body can cure itself."},
    {"e": "hormone replacement therapy", "t": "hormon replasman tedavisi", "c": "Tedavi & İlaç", "x": "HRT is a medication that contains female hormones, used to treat menopausal symptoms."},
    {"e": "hospice care", "t": "terminal dönem bakımı", "c": "Tedavi & İlaç", "x": "Hospice care focuses on the quality of life for people and their caregivers who are experiencing an advanced, life-limiting illness."},
    {"e": "hysterectomy", "t": "rahim alınması", "c": "Tedavi & İlaç", "x": "A hysterectomy is a surgical operation to remove all or part of the uterus."},
    {"e": "immunization", "t": "aşılama", "c": "Tedavi & İlaç", "x": "Immunization protects people against harmful infections before they come into contact with them."},
    {"e": "immunotherapy", "t": "immünoterapi", "c": "Tedavi & İlaç", "x": "Immunotherapy is a type of cancer treatment that helps your immune system fight cancer."},
    {"e": "implant", "t": "implant", "c": "Tedavi & İlaç", "x": "A cochlear implant can provide a sense of sound to a person who is profoundly deaf."},
    {"e": "incision", "t": "kesi", "c": "Tedavi & İlaç", "x": "The surgeon made a small incision in the patient's abdomen."},
    {"e": "inhaler", "t": "inhaler (sprey)", "c": "Tedavi & İlaç", "x": "Asthma inhalers are hand-held, portable devices that deliver medication to your lungs."},
    {"e": "injection", "t": "enjeksiyon", "c": "Tedavi & İlaç", "x": "The vaccine is given by injection into the muscle of the upper arm."},
    {"e": "insulin", "t": "insülin", "c": "Tedavi & İlaç", "x": "People with type 1 diabetes need insulin therapy to survive."},
    {"e": "intravenous", "t": "damar içi (IV)", "c": "Tedavi & İlaç", "x": "Intravenous fluids are specially formulated liquids that are injected into a vein."},
    {"e": "laparoscopy", "t": "laparoskopi", "c": "Tedavi & İlaç", "x": "Laparoscopy is a type of surgical procedure that allows a surgeon to access the inside of the abdomen and pelvis without having to make large incisions."},
    {"e": "laxative", "t": "müshil", "c": "Tedavi & İlaç", "x": "Laxatives are a type of medicine that can treat constipation."},
    {"e": "ligature", "t": "ligatür", "c": "Tedavi & İlaç", "x": "A ligature is a piece of thread or wire tied around a blood vessel to stop bleeding."},
    {"e": "liposuction", "t": "liposuction", "c": "Tedavi & İlaç", "x": "Liposuction is a surgical procedure that uses a suction technique to remove fat from specific areas of the body."},
    {"e": "lumpectomy", "t": "lumpektomi", "c": "Tedavi & İlaç", "x": "A lumpectomy is a surgery to remove cancer or other abnormal tissue from your breast."},
    {"e": "mammogram", "t": "mamografi", "c": "Tedavi & İlaç", "x": "A mammogram is an X-ray picture of the breast used to check for breast cancer."},
    {"e": "mastectomy", "t": "mastektomi", "c": "Tedavi & İlaç", "x": "Mastectomy is breast cancer surgery that removes the entire breast."},
    {"e": "medication", "t": "ilaç", "c": "Tedavi & İlaç", "x": "Be sure to take your medication exactly as prescribed by your doctor."},
    {"e": "narcotic", "t": "narkotik", "c": "Tedavi & İlaç", "x": "Narcotics are powerful painkillers that can also cause drowsiness and changes in mood."},
    {"e": "ointment", "t": "merhem", "c": "Tedavi & İlaç", "x": "Apply the antibiotic ointment to the wound twice a day."},
    {"e": "pacemaker", "t": "kalp pili", "c": "Tedavi & İlaç", "x": "A pacemaker is a small device that's placed in the chest or abdomen to help control abnormal heart rhythms."},
    {"e": "palliative care", "t": "palyatif bakım", "c": "Tedavi & İlaç", "x": "Palliative care is specialized medical care for people living with a serious illness."},
    {"e": "physiotherapy", "t": "fizik tedavi", "c": "Tedavi & İlaç", "x": "Physiotherapy helps to restore movement and function when someone is affected by injury, illness or disability."},
    {"e": "placebo", "t": "plasebo", "c": "Tedavi & İlaç", "x": "The placebo effect is a beneficial health outcome resulting from a person's anticipation that an intervention will help."},
    {"e": "prescription", "t": "reçete", "c": "Tedavi & İlaç", "x": "You will need a prescription from your doctor to get this medicine."},
    {"e": "prosthesis", "t": "protez", "c": "Tedavi & İlaç", "x": "A prosthesis is an artificial device that replaces a missing body part."},
    {"e": "radiation therapy", "t": "radyoterapi", "c": "Tedavi & İlaç", "x": "Radiation therapy is a type of cancer treatment that uses high doses of radiation to kill cancer cells."},
    {"e": "radiography", "t": "röntgen çekimi", "c": "Tedavi & İlaç", "x": "Radiography is an imaging technique using X-rays to view the internal form of an object."},
    {"e": "rehabilitation", "t": "rehabilitasyon", "c": "Tedavi & İlaç", "x": "Cardiac rehabilitation is a medically supervised program designed to improve your cardiovascular health."},
    {"e": "resuscitation", "t": "resüsitasyon", "c": "Tedavi & İlaç", "x": "Cardiopulmonary resuscitation (CPR) can help save a life during a cardiac or breathing emergency."},
    {"e": "scalpel", "t": "neşter", "c": "Tedavi & İlaç", "x": "The surgeon asked the nurse to hand him the scalpel."},
    {"e": "sedative", "t": "sakinleştirici", "c": "Tedavi & İlaç", "x": "A sedative was administered to help the patient relax before the procedure."},
    {"e": "stethoscope", "t": "stetoskop", "c": "Tedavi & İlaç", "x": "The doctor used a stethoscope to listen to the patient's heart and lungs."},
    {"e": "suppository", "t": "fitil", "c": "Tedavi & İlaç", "x": "A suppository is another way to deliver a drug when the oral route is not viable."},
    {"e": "surgery", "t": "ameliyat", "c": "Tedavi & İlaç", "x": "The patient required emergency surgery to repair the ruptured spleen."},
    {"e": "suture", "t": "dikiş", "c": "Tedavi & İlaç", "x": "Sutures are used to hold body tissues together after an injury or surgery."},
    {"e": "syringe", "t": "şırınga", "c": "Tedavi & İlaç", "x": "The nurse prepared the syringe for the vaccination."},
    {"e": "therapy", "t": "terapi", "c": "Tedavi & İlaç", "x": "Physical therapy can help improve mobility and relieve pain."},
    {"e": "tourniquet", "t": "turnike", "c": "Tedavi & İlaç", "x": "A tourniquet was applied to the patient's arm to stop the severe bleeding."},
    {"e": "transfusion", "t": "kan nakli", "c": "Tedavi & İlaç", "x": "Blood transfusions are used to replace blood lost during surgery or due to a serious injury."},
    {"e": "transplant", "t": "organ nakli", "c": "Tedavi & İlaç", "x": "A kidney transplant is often the best treatment for kidney failure."},
    {"e": "ultrasound", "t": "ultrason", "c": "Tedavi & İlaç", "x": "An ultrasound scan is often used to monitor the development of the fetus during pregnancy."},
    {"e": "vaccine", "t": "aşı", "c": "Tedavi & İlaç", "x": "The measles vaccine is highly effective at preventing the disease."},
    {"e": "ventilator", "t": "solunum cihazı", "c": "Tedavi & İlaç", "x": "A ventilator is a machine that helps you breathe when you can't breathe on your own."},

    // --- General Medical & Academic ---
    {"e": "abstinence", "t": "perhiz", "c": "Genel Tıp", "x": "Abstinence from alcohol is recommended for patients with liver disease."},
    {"e": "adhere", "t": "bağlı kalmak", "c": "Genel Tıp", "x": "It is crucial for patients to adhere to their prescribed medication regimen."},
    {"e": "adolescent", "t": "ergen", "c": "Genel Tıp", "x": "Adolescent psychology focuses on the mental health issues specific to teenagers."},
    {"e": "alleviate", "t": "hafifletmek", "c": "Genel Tıp", "x": "Painkillers were prescribed to alleviate the patient's suffering."},
    {"e": "anomaly", "t": "anomali", "c": "Genel Tıp", "x": "The ultrasound detected a congenital anomaly in the fetus's heart."},
    {"e": "assess", "t": "değerlendirmek", "c": "Genel Tıp", "x": "The doctor will assess your symptoms before making a diagnosis."},
    {"e": "asymmetrical", "t": "asimetrik", "c": "Genel Tıp", "x": "Asymmetrical moles can be a warning sign of melanoma."},
    {"e": "attending physician", "t": "uzman hekim", "c": "Genel Tıp", "x": "The attending physician is ultimately responsible for the patient's care."},
    {"e": "bacterial", "t": "bakteriyel", "c": "Genel Tıp", "x": "Bacterial infections can usually be treated with antibiotics."},
    {"e": "carrier", "t": "taşıyıcı", "c": "Genel Tıp", "x": "He is an asymptomatic carrier of the genetic mutation."},
    {"e": "clinical trial", "t": "klinik deney", "c": "Genel Tıp", "x": "The new cancer drug is currently in phase III clinical trials."},
    {"e": "cognition", "t": "biliş", "c": "Genel Tıp", "x": "Alzheimer's disease progressively destroys memory and cognition."},
    {"e": "comorbid", "t": "eşlik eden hastalık", "c": "Genel Tıp", "x": "Depression is a common comorbid condition in patients with chronic pain."},
    {"e": "contagious", "t": "bulaşıcı", "c": "Genel Tıp", "x": "Measles is a highly contagious disease."},
    {"e": "contraindication", "t": "kontrendikasyon", "c": "Genel Tıp", "x": "Pregnancy is a strict contraindication for this medication."},
    {"e": "deficiency", "t": "eksiklik", "c": "Genel Tıp", "x": "Vitamin D deficiency can lead to bone problems such as rickets."},
    {"e": "degenerate", "t": "yozlaşmak", "c": "Genel Tıp", "x": "In Parkinson's disease, certain neurons in the brain gradually degenerate."},
    {"e": "deteriorate", "t": "kötüleşmek", "c": "Genel Tıp", "x": "The patient's condition began to deteriorate rapidly after the surgery."},
    {"e": "discrepancy", "t": "tutarsızlık", "c": "Genel Tıp", "x": "There was a discrepancy between the lab results and the clinical findings."},
    {"e": "disorder", "t": "bozukluk", "c": "Genel Tıp", "x": "Bipolar disorder is characterized by extreme mood swings."},
    {"e": "dominant trait", "t": "baskın özellik", "c": "Genel Tıp", "x": "Brown eyes are a dominant trait over blue eyes."},
    {"e": "dormant", "t": "inaktif", "c": "Genel Tıp", "x": "The virus can remain dormant in the body for years before causing symptoms."},
    {"e": "efficacy", "t": "etkililik", "c": "Genel Tıp", "x": "The clinical trials demonstrated the efficacy of the new vaccine."},
    {"e": "elicit", "t": "meydana çıkarmak", "c": "Genel Tıp", "x": "The doctor asked specific questions to elicit a detailed medical history."},
    {"e": "empirical", "t": "ampirik", "c": "Genel Tıp", "x": "Empirical therapy involves starting treatment before a firm diagnosis is made."},
    {"e": "epidemiology", "t": "epidemiyoloji", "c": "Genel Tıp", "x": "Epidemiology is crucial for understanding how diseases spread in populations."},
    {"e": "erratic", "t": "düzensiz", "c": "Genel Tıp", "x": "The patient exhibited erratic behavior following the head injury."},
    {"e": "excrete", "t": "boşaltmak", "c": "Genel Tıp", "x": "The kidneys excrete waste products and excess water as urine."},
    {"e": "fatal", "t": "ölümcül", "c": "Genel Tıp", "x": "Rabies is almost always fatal once clinical symptoms appear."},
    {"e": "gene", "t": "gen", "c": "Genel Tıp", "x": "BRCA1 and BRCA2 are genes that, when mutated, increase the risk of breast cancer."},
    {"e": "genetic counseling", "t": "genetik danışmanlık", "c": "Genel Tıp", "x": "Genetic counseling is recommended for couples with a family history of cystic fibrosis."},
    {"e": "geriatrics", "t": "geriatri", "c": "Genel Tıp", "x": "Geriatrics focuses on the health care of elderly people."},
    {"e": "gestation", "t": "gebelik süresi", "c": "Genel Tıp", "x": "The normal gestation period for humans is about 40 weeks."},
    {"e": "hereditary", "t": "kalıtsal", "c": "Genel Tıp", "x": "Huntington's disease is a hereditary neurodegenerative disorder."},
    {"e": "hierarchy", "t": "hiyerarşi", "c": "Genel Tıp", "x": "There is a strict hierarchy of medical staff in a teaching hospital."},
    {"e": "hygiene", "t": "hijyen", "c": "Genel Tıp", "x": "Good hand hygiene is the most effective way to prevent the spread of infections."},
    {"e": "hypothesis", "t": "hipotez", "c": "Genel Tıp", "x": "The study was designed to test the hypothesis that the new drug is more effective."},
    {"e": "impairment", "t": "hasar", "c": "Genel Tıp", "x": "Visual impairment can significantly affect a person's quality of life."},
    {"e": "in vitro", "t": "in vitro", "c": "Genel Tıp", "x": "In vitro fertilization (IVF) is a complex series of procedures used to help with fertility."},
    {"e": "in vivo", "t": "in vivo", "c": "Genel Tıp", "x": "Animal models are often used for in vivo studies of new drugs."},
    {"e": "incubation", "t": "kuluçka", "c": "Genel Tıp", "x": "The incubation period of the virus ranges from two to fourteen days."},
    {"e": "induce", "t": "tetiklemek", "c": "Genel Tıp", "x": "The doctor decided to induce labor because the baby was overdue."},
    {"e": "inevitable", "t": "kaçınılmaz", "c": "Genel Tıp", "x": "Without treatment, progressive vision loss is inevitable in patients with glaucoma."},
    {"e": "infectious", "t": "bulaşıcı", "c": "Genel Tıp", "x": "Tuberculosis is an infectious disease that mainly affects the lungs."},
    {"e": "infer", "t": "çıkarım yapmak", "c": "Genel Tıp", "x": "From the blood test results, the doctor could infer that the patient had an infection."},
    {"e": "inherent", "t": "doğasında olan", "c": "Genel Tıp", "x": "There are inherent risks associated with any surgical procedure."},
    {"e": "innate", "t": "doğuştan gelen", "c": "Genel Tıp", "x": "The innate immune system is the body's first line of defense against pathogens."},
    {"e": "intervention", "t": "müdahale", "c": "Genel Tıp", "x": "Early medical intervention can prevent permanent damage after a stroke."},
    {"e": "invasive", "t": "invaziv", "c": "Genel Tıp", "x": "Open-heart surgery is a highly invasive procedure."},
    {"e": "latent", "t": "gizli", "c": "Genel Tıp", "x": "A person with latent tuberculosis infection does not feel sick and cannot spread TB to others."},
    {"e": "lethal", "t": "ölümcül", "c": "Genel Tıp", "x": "A lethal dose of the medication can cause respiratory arrest."},
    {"e": "longevity", "t": "uzun ömürlülük", "c": "Genel Tıp", "x": "Advances in public health have significantly increased human longevity."},
    {"e": "malpractice", "t": "tıbbi hata", "c": "Genel Tıp", "x": "The surgeon was sued for medical malpractice after leaving a sponge in the patient."},
    {"e": "manifestation", "t": "tezahür", "c": "Genel Tıp", "x": "Fever is a common clinical manifestation of an infection."},
    {"e": "microbiome", "t": "mikrobiyom", "c": "Genel Tıp", "x": "The human gut microbiome plays a crucial role in health and disease."},
    {"e": "mutation", "t": "mutasyon", "c": "Genel Tıp", "x": "A genetic mutation is responsible for cystic fibrosis."},
    {"e": "neonatal", "t": "yeni doğan ile ilgili", "c": "Genel Tıp", "x": "The premature baby was cared for in the neonatal intensive care unit (NICU)."},
    {"e": "neurology", "t": "nöroloji", "c": "Genel Tıp", "x": "Neurology is the branch of medicine dealing with disorders of the nervous system."},
    {"e": "noninvasive", "t": "girişimsel olmayan", "c": "Genel Tıp", "x": "Ultrasound is a noninvasive diagnostic tool."},
    {"e": "nutrition", "t": "beslenme", "c": "Genel Tıp", "x": "Good nutrition is essential for growth and development in children."},
    {"e": "obese", "t": "obez", "c": "Genel Tıp", "x": "Obese individuals are at a higher risk for type 2 diabetes and heart disease."},
    {"e": "obstetrics", "t": "obstetrik", "c": "Genel Tıp", "x": "Obstetrics is the field of study concentrated on pregnancy, childbirth and the postpartum period."},
    {"e": "oncology", "t": "onkoloji", "c": "Genel Tıp", "x": "Oncology focuses on the diagnosis and treatment of cancer."},
    {"e": "outpatient", "t": "ayakta tedavi gören hasta", "c": "Genel Tıp", "x": "The clinic provides outpatient services for minor injuries and illnesses."},
    {"e": "palliative", "t": "palyatif", "c": "Genel Tıp", "x": "Palliative care aims to improve the quality of life for patients with serious illnesses."},
    {"e": "pathology", "t": "patoloji", "c": "Genel Tıp", "x": "Pathology involves the laboratory examination of samples of body tissue for diagnostic purposes."},
    {"e": "pediatrics", "t": "pediatri", "c": "Genel Tıp", "x": "Pediatrics is the branch of medicine that involves the medical care of infants, children, and adolescents."},
    {"e": "precursor", "t": "öncül", "c": "Genel Tıp", "x": "Elevated cholesterol levels are often a precursor to cardiovascular disease."},
    {"e": "predisposition", "t": "yatkınlık", "c": "Genel Tıp", "x": "A family history of breast cancer indicates a genetic predisposition to the disease."},
    {"e": "preventive", "t": "koruyucu", "c": "Genel Tıp", "x": "Preventive medicine focuses on keeping people healthy and preventing disease."},
    {"e": "proliferation", "t": "hızla çoğalma", "c": "Genel Tıp", "x": "Cancer is characterized by the uncontrolled proliferation of abnormal cells."},
    {"e": "prophylactic", "t": "koruyucu (profilaktik)", "c": "Genel Tıp", "x": "Prophylactic antibiotics were given before surgery to prevent infection."},
    {"e": "psychiatry", "t": "psikiyatri", "c": "Genel Tıp", "x": "Psychiatry is the medical specialty devoted to the diagnosis, prevention, and treatment of mental disorders."},
    {"e": "quarantine", "t": "karantina", "c": "Genel Tıp", "x": "Strict quarantine measures were implemented to control the outbreak."},
    {"e": "radiology", "t": "radyoloji", "c": "Genel Tıp", "x": "Radiology uses imaging technology to diagnose and treat diseases."},
    {"e": "recessive trait", "t": "çekinik özellik", "c": "Genel Tıp", "x": "Blue eyes are a recessive trait, requiring two copies of the gene to be expressed."},
    {"e": "recuperate", "t": "iyileşmek", "c": "Genel Tıp", "x": "It will take several weeks to fully recuperate from the pneumonia."},
    {"e": "regimen", "t": "tedavi programı", "c": "Genel Tıp", "x": "The doctor prescribed a strict regimen of diet and exercise."},
    {"e": "renal", "t": "böbrekle ilgili", "c": "Genel Tıp", "x": "Chronic renal failure often requires dialysis or a kidney transplant."},
    {"e": "resilience", "t": "direnç", "c": "Genel Tıp", "x": "Psychological resilience helps individuals cope with stress and trauma."},
    {"e": "respiratory", "t": "solunumla ilgili", "c": "Genel Tıp", "x": "COVID-19 is primarily a respiratory illness."},
    {"e": "resuscitate", "t": "hayata döndürmek", "c": "Genel Tıp", "x": "Paramedics attempted to resuscitate the victim at the scene."},
    {"e": "screening", "t": "tarama", "c": "Genel Tıp", "x": "Regular screening can detect cervical cancer at an early, treatable stage."},
    {"e": "secrete", "t": "salgılamak", "c": "Genel Tıp", "x": "The pancreas secretes insulin into the bloodstream."},
    {"e": "sedentary", "t": "hareketsiz", "c": "Genel Tıp", "x": "A sedentary lifestyle is a major risk factor for cardiovascular disease."},
    {"e": "susceptible", "t": "duyarlı", "c": "Genel Tıp", "x": "Elderly individuals are more susceptible to severe complications from the flu."},
    {"e": "symptomatic", "t": "belirti gösteren", "c": "Genel Tıp", "x": "Treatment is usually only recommended for symptomatic patients."},
    {"e": "systemic", "t": "sistematik", "c": "Genel Tıp", "x": "Systemic lupus erythematosus can affect multiple organs in the body."},
    {"e": "terminal", "t": "son evre", "c": "Genel Tıp", "x": "Terminal illness refers to a disease that cannot be cured or adequately treated."},
    {"e": "therapeutic", "t": "tedavi edici", "c": "Genel Tıp", "x": "Massage can have a therapeutic effect on tense muscles."},
    {"e": "toxicity", "t": "zehirlilik", "c": "Genel Tıp", "x": "The toxicity of the drug requires careful monitoring of liver function."},
    {"e": "transmission", "t": "bulaşma", "c": "Genel Tıp", "x": "Using condoms can prevent the sexual transmission of HIV."},
    {"e": "trauma", "t": "travma", "c": "Genel Tıp", "x": "Physical trauma from the car accident resulted in multiple fractures."},
    {"e": "trigger", "t": "tetiklemek", "c": "Genel Tıp", "x": "Pollen and dust mites can trigger an asthma attack."},
    {"e": "vector", "t": "taşıyıcı", "c": "Genel Tıp", "x": "Ticks are the vector for Lyme disease."},
    {"e": "virology", "t": "virüs bilimi", "c": "Genel Tıp", "x": "Virology is the study of viruses and viral diseases."},
    {"e": "vital", "t": "hayati", "c": "Genel Tıp", "x": "The heart and lungs are vital organs."},
    {"e": "withdrawal", "t": "yoksunluk", "c": "Genel Tıp", "x": "Alcohol withdrawal can cause tremors, anxiety, and seizures."}
  ];

  final existingEnglishTerms = data.map((item) => (item['e'] as String).toLowerCase()).toSet();
  int addedCount = 0;

  for (var term in newTerms) {
    if (!existingEnglishTerms.contains((term['e'] as String).toLowerCase())) {
      data.add(term);
      existingEnglishTerms.add((term['e'] as String).toLowerCase());
      addedCount++;
    }
  }

  print('Adding \$addedCount new unique terms.');
  print('New total: \${data.length}');

  final encoder = JsonEncoder.withIndent('  ');
  // Re-encode to compact if user prefers compact, but wait, the fallback data was a single line
  // Let's just write standard compacted JSON to match the original single line, or a bit readable
  await existingFile.writeAsString(jsonEncode(data));

  print('Done.');
}
