workflows:
  android-workflow:
    name: Şüko YÖKDİL Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  ios-workflow:
    name: Şüko YÖKDİL iOS TestFlight Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.sukolovote.yokdilSaglik"
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch/create signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Apply provisioning profiles to Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
