const fs = require('fs');
const path = require('path');

// 500+ YOKDiL Saglik terimleri - kategorilere ayrilmis
const terms = [
  // === ANATOMI (70+) ===
  {e:"cardiovascular system",t:"kardiyovasküler sistem",c:"Anatomi",x:"The cardiovascular system circulates blood throughout the body."},
  {e:"respiratory tract",t:"solunum yolu",c:"Anatomi",x:"Upper respiratory tract infections are common in winter."},
  {e:"gastrointestinal tract",t:"sindirim kanalı",c:"Anatomi",x:"The gastrointestinal tract extends from the mouth to the anus."},
  {e:"musculoskeletal system",t:"kas-iskelet sistemi",c:"Anatomi",x:"The musculoskeletal system provides support and movement."},
  {e:"nervous system",t:"sinir sistemi",c:"Anatomi",x:"The nervous system controls all bodily functions."},
  {e:"endocrine system",t:"endokrin sistem",c:"Anatomi",x:"The endocrine system produces hormones that regulate metabolism."},
  {e:"lymph node",t:"lenf düğümü",c:"Anatomi",x:"Swollen lymph nodes may indicate an infection."},
  {e:"bone marrow",t:"kemik iliği",c:"Anatomi",x:"Bone marrow produces red blood cells and white blood cells."},
  {e:"cerebral cortex",t:"beyin kabuğu",c:"Anatomi",x:"The cerebral cortex is responsible for higher brain functions."},
  {e:"spinal cord",t:"omurilik",c:"Anatomi",x:"Damage to the spinal cord can result in paralysis."},
  {e:"artery",t:"atardamar",c:"Anatomi",x:"The coronary artery supplies blood to the heart muscle."},
  {e:"vein",t:"toplardamar",c:"Anatomi",x:"Blood returns to the heart through veins."},
  {e:"capillary",t:"kılcal damar",c:"Anatomi",x:"Gas exchange occurs in the capillaries of the lungs."},
  {e:"tissue",t:"doku",c:"Anatomi",x:"Connective tissue provides structural support to organs."},
  {e:"organ",t:"organ",c:"Anatomi",x:"The liver is the largest internal organ in the body."},
  {e:"cell membrane",t:"hücre zarı",c:"Anatomi",x:"The cell membrane controls what enters and exits the cell."},
  {e:"thorax",t:"göğüs kafesi",c:"Anatomi",x:"The thorax protects the heart and lungs."},
  {e:"abdomen",t:"karın bölgesi",c:"Anatomi",x:"The patient reported severe pain in the lower abdomen."},
  {e:"pelvis",t:"leğen kemiği",c:"Anatomi",x:"A fracture of the pelvis may require surgical intervention."},
  {e:"vertebra",t:"omur",c:"Anatomi",x:"Each vertebra is separated by an intervertebral disc."},
  {e:"diaphragm",t:"diyafram",c:"Anatomi",x:"The diaphragm is the primary muscle used in breathing."},
  {e:"esophagus",t:"yemek borusu",c:"Anatomi",x:"Food travels down the esophagus to the stomach."},
  {e:"trachea",t:"soluk borusu",c:"Anatomi",x:"The trachea carries air from the larynx to the bronchi."},
  {e:"bronchi",t:"bronşlar",c:"Anatomi",x:"The bronchi branch into smaller airways called bronchioles."},
  {e:"alveoli",t:"alveoller",c:"Anatomi",x:"Oxygen diffuses into the blood through the walls of the alveoli."},
  {e:"pancreas",t:"pankreas",c:"Anatomi",x:"The pancreas produces insulin to regulate blood sugar levels."},
  {e:"thyroid gland",t:"tiroid bezi",c:"Anatomi",x:"The thyroid gland regulates metabolism through hormone secretion."},
  {e:"adrenal gland",t:"böbreküstü bezi",c:"Anatomi",x:"The adrenal glands produce cortisol in response to stress."},
  {e:"pituitary gland",t:"hipofiz bezi",c:"Anatomi",x:"The pituitary gland is often called the master gland."},
  {e:"hypothalamus",t:"hipotalamus",c:"Anatomi",x:"The hypothalamus maintains body temperature and hunger signals."},
  {e:"cerebellum",t:"beyincik",c:"Anatomi",x:"The cerebellum coordinates voluntary muscle movements."},
  {e:"hippocampus",t:"hipokampüs",c:"Anatomi",x:"The hippocampus plays a key role in memory formation."},
  {e:"ligament",t:"bağ",c:"Anatomi",x:"A torn ligament often requires months of rehabilitation."},
  {e:"tendon",t:"tendon",c:"Anatomi",x:"The Achilles tendon connects the calf muscle to the heel bone."},
  {e:"cartilage",t:"kıkırdak",c:"Anatomi",x:"Cartilage acts as a cushion between joints."},
  {e:"sternum",t:"göğüs kemiği",c:"Anatomi",x:"The sternum protects the heart and major blood vessels."},
  {e:"clavicle",t:"köprücük kemiği",c:"Anatomi",x:"A fractured clavicle is a common sports injury."},
  {e:"femur",t:"uyluk kemiği",c:"Anatomi",x:"The femur is the longest and strongest bone in the body."},
  {e:"tibia",t:"kaval kemiği",c:"Anatomi",x:"The tibia bears most of the body weight in the lower leg."},
  {e:"scapula",t:"kürek kemiği",c:"Anatomi",x:"The scapula connects the upper arm bone to the collarbone."},
  {e:"ribcage",t:"göğüs kafesi",c:"Anatomi",x:"The ribcage encloses and protects the thoracic cavity organs."},
  {e:"duodenum",t:"onikiparmak bağırsağı",c:"Anatomi",x:"The duodenum is the first section of the small intestine."},
  {e:"colon",t:"kalın bağırsak",c:"Anatomi",x:"The colon absorbs water and electrolytes from digested food."},
  {e:"rectum",t:"rektum",c:"Anatomi",x:"The rectum stores feces before they are eliminated."},
  {e:"bladder",t:"mesane",c:"Anatomi",x:"The bladder stores urine until it is excreted from the body."},
  {e:"kidney",t:"böbrek",c:"Anatomi",x:"The kidneys filter waste products from the blood."},
  {e:"liver",t:"karaciğer",c:"Anatomi",x:"The liver detoxifies chemicals and metabolizes drugs."},
  {e:"spleen",t:"dalak",c:"Anatomi",x:"The spleen filters blood and helps fight certain bacteria."},
  {e:"gallbladder",t:"safra kesesi",c:"Anatomi",x:"The gallbladder stores bile produced by the liver."},
  {e:"appendix",t:"apandis",c:"Anatomi",x:"Inflammation of the appendix is known as appendicitis."},
  {e:"pharynx",t:"yutak",c:"Anatomi",x:"The pharynx serves as a passageway for both food and air."},
  {e:"larynx",t:"gırtlak",c:"Anatomi",x:"The larynx contains the vocal cords and produces sound."},
  {e:"aorta",t:"aort",c:"Anatomi",x:"The aorta is the largest artery in the human body."},
  {e:"ventricle",t:"karıncık",c:"Anatomi",x:"The left ventricle pumps oxygenated blood to the body."},
  {e:"atrium",t:"kulakçık",c:"Anatomi",x:"The right atrium receives deoxygenated blood from the body."},
  {e:"cornea",t:"kornea",c:"Anatomi",x:"The cornea refracts light entering the eye."},
  {e:"retina",t:"retina",c:"Anatomi",x:"The retina converts light into neural signals for the brain."},
  {e:"cochlea",t:"koklea",c:"Anatomi",x:"The cochlea is the auditory portion of the inner ear."},
  {e:"synapse",t:"sinaps",c:"Anatomi",x:"Neurotransmitters cross the synapse to transmit nerve impulses."},
  {e:"neuron",t:"nöron",c:"Anatomi",x:"A neuron transmits electrical impulses throughout the body."},
  {e:"platelet",t:"trombosit",c:"Anatomi",x:"Platelets help form blood clots to stop bleeding."},
  {e:"plasma",t:"plazma",c:"Anatomi",x:"Plasma makes up about 55 percent of total blood volume."},
  {e:"hemoglobin",t:"hemoglobin",c:"Anatomi",x:"Hemoglobin carries oxygen from the lungs to body tissues."},
  {e:"white blood cell",t:"akyuvar",c:"Anatomi",x:"White blood cells are essential for fighting infections."},
  {e:"red blood cell",t:"alyuvar",c:"Anatomi",x:"Red blood cells transport oxygen to all parts of the body."},

  // === HASTALIKLAR (80+) ===
  {e:"chronic disease",t:"kronik hastalık",c:"Hastalıklar",x:"Chronic diseases require long-term management and care."},
  {e:"infectious disease",t:"bulaşıcı hastalık",c:"Hastalıklar",x:"Infectious diseases spread from person to person."},
  {e:"autoimmune disorder",t:"otoimmün bozukluk",c:"Hastalıklar",x:"In autoimmune disorders, the body attacks its own tissues."},
  {e:"cardiovascular disease",t:"kalp-damar hastalığı",c:"Hastalıklar",x:"Cardiovascular disease is the leading cause of death worldwide."},
  {e:"diabetes mellitus",t:"şeker hastalığı",c:"Hastalıklar",x:"Type 2 diabetes mellitus is strongly associated with obesity."},
  {e:"hypertension",t:"hipertansiyon",c:"Hastalıklar",x:"Uncontrolled hypertension increases the risk of stroke."},
  {e:"stroke",t:"inme / felç",c:"Hastalıklar",x:"A stroke occurs when blood supply to the brain is interrupted."},
  {e:"heart attack",t:"kalp krizi",c:"Hastalıklar",x:"Chest pain is a common symptom of a heart attack."},
  {e:"pneumonia",t:"zatürre",c:"Hastalıklar",x:"Pneumonia is an infection that inflames the air sacs in the lungs."},
  {e:"tuberculosis",t:"tüberküloz / verem",c:"Hastalıklar",x:"Tuberculosis primarily affects the lungs and is highly contagious."},
  {e:"asthma",t:"astım",c:"Hastalıklar",x:"Asthma causes the airways to narrow and produce extra mucus."},
  {e:"bronchitis",t:"bronşit",c:"Hastalıklar",x:"Chronic bronchitis involves a long-term cough with mucus."},
  {e:"hepatitis",t:"hepatit",c:"Hastalıklar",x:"Hepatitis B can be prevented through vaccination."},
  {e:"cirrhosis",t:"siroz",c:"Hastalıklar",x:"Cirrhosis is late-stage scarring of the liver."},
  {e:"anemia",t:"anemi / kansızlık",c:"Hastalıklar",x:"Iron deficiency anemia is the most common type of anemia."},
  {e:"leukemia",t:"lösemi",c:"Hastalıklar",x:"Leukemia is a cancer of the blood-forming tissues."},
  {e:"malignant tumor",t:"habis tümör",c:"Hastalıklar",x:"A malignant tumor can invade nearby tissues and spread."},
  {e:"benign tumor",t:"iyi huylu tümör",c:"Hastalıklar",x:"A benign tumor does not spread to other parts of the body."},
  {e:"metastasis",t:"metastaz",c:"Hastalıklar",x:"Metastasis occurs when cancer spreads to distant organs."},
  {e:"epilepsy",t:"epilepsi / sara",c:"Hastalıklar",x:"Epilepsy is characterized by recurrent seizures."},
  {e:"Alzheimer's disease",t:"Alzheimer hastalığı",c:"Hastalıklar",x:"Alzheimer's disease causes progressive memory loss."},
  {e:"Parkinson's disease",t:"Parkinson hastalığı",c:"Hastalıklar",x:"Parkinson's disease affects movement and coordination."},
  {e:"arthritis",t:"artrit / eklem iltihabı",c:"Hastalıklar",x:"Rheumatoid arthritis is an autoimmune condition."},
  {e:"osteoporosis",t:"osteoporoz / kemik erimesi",c:"Hastalıklar",x:"Osteoporosis makes bones fragile and more likely to fracture."},
  {e:"obesity",t:"obezite",c:"Hastalıklar",x:"Obesity is a major risk factor for type 2 diabetes."},
  {e:"malnutrition",t:"yetersiz beslenme",c:"Hastalıklar",x:"Malnutrition weakens the immune system and delays recovery."},
  {e:"allergy",t:"alerji",c:"Hastalıklar",x:"Food allergies can cause severe anaphylactic reactions."},
  {e:"inflammation",t:"iltihap / enflamasyon",c:"Hastalıklar",x:"Inflammation is the body's natural response to injury."},
  {e:"infection",t:"enfeksiyon",c:"Hastalıklar",x:"Bacterial infections are usually treated with antibiotics."},
  {e:"sepsis",t:"sepsis / kan zehirlenmesi",c:"Hastalıklar",x:"Sepsis is a life-threatening response to infection."},
  {e:"thrombosis",t:"tromboz",c:"Hastalıklar",x:"Deep vein thrombosis can lead to pulmonary embolism."},
  {e:"embolism",t:"emboli",c:"Hastalıklar",x:"Pulmonary embolism blocks blood flow to the lungs."},
  {e:"hemorrhage",t:"kanama",c:"Hastalıklar",x:"Internal hemorrhage requires immediate medical attention."},
  {e:"ulcer",t:"ülser",c:"Hastalıklar",x:"Gastric ulcers are often caused by H. pylori bacteria."},
  {e:"hernia",t:"fıtık",c:"Hastalıklar",x:"An inguinal hernia occurs in the groin area."},
  {e:"fracture",t:"kırık",c:"Hastalıklar",x:"A compound fracture breaks through the skin surface."},
  {e:"concussion",t:"beyin sarsıntısı",c:"Hastalıklar",x:"A concussion is a traumatic brain injury caused by a blow."},
  {e:"edema",t:"ödem",c:"Hastalıklar",x:"Edema is the accumulation of excess fluid in body tissues."},
  {e:"fibrosis",t:"fibroz",c:"Hastalıklar",x:"Pulmonary fibrosis causes scarring of the lung tissue."},
  {e:"necrosis",t:"nekroz",c:"Hastalıklar",x:"Tissue necrosis results from a lack of blood supply."},
  {e:"abscess",t:"apse",c:"Hastalıklar",x:"An abscess is a collection of pus caused by infection."},
  {e:"cyst",t:"kist",c:"Hastalıklar",x:"An ovarian cyst is a fluid-filled sac on the ovary."},
  {e:"syndrome",t:"sendrom",c:"Hastalıklar",x:"Metabolic syndrome increases the risk of heart disease."},
  {e:"dehydration",t:"dehidrasyon / su kaybı",c:"Hastalıklar",x:"Severe dehydration can lead to kidney failure."},
  {e:"jaundice",t:"sarılık",c:"Hastalıklar",x:"Jaundice causes yellowing of the skin and eyes."},
  {e:"meningitis",t:"menenjit",c:"Hastalıklar",x:"Bacterial meningitis is a medical emergency."},
  {e:"gastritis",t:"gastrit",c:"Hastalıklar",x:"Chronic gastritis can lead to stomach ulcers."},
  {e:"dermatitis",t:"dermatit",c:"Hastalıklar",x:"Contact dermatitis causes skin redness and itching."},
  {e:"conjunctivitis",t:"konjonktivit",c:"Hastalıklar",x:"Conjunctivitis is commonly known as pink eye."},
  {e:"otitis media",t:"orta kulak iltihabı",c:"Hastalıklar",x:"Otitis media is very common in young children."},
  {e:"tonsillitis",t:"bademcik iltihabı",c:"Hastalıklar",x:"Recurring tonsillitis may require surgical removal."},
  {e:"sinusitis",t:"sinüzit",c:"Hastalıklar",x:"Sinusitis causes inflammation of the sinus cavities."},
  {e:"renal failure",t:"böbrek yetmezliği",c:"Hastalıklar",x:"Chronic renal failure may require dialysis treatment."},
  {e:"heart failure",t:"kalp yetmezliği",c:"Hastalıklar",x:"Heart failure means the heart cannot pump blood efficiently."},
  {e:"respiratory failure",t:"solunum yetmezliği",c:"Hastalıklar",x:"Acute respiratory failure requires mechanical ventilation."},
  {e:"pancreatitis",t:"pankreatit",c:"Hastalıklar",x:"Acute pancreatitis causes severe abdominal pain."},
  {e:"appendicitis",t:"apandisit",c:"Hastalıklar",x:"Appendicitis typically requires emergency surgery."},
  {e:"peritonitis",t:"peritonit",c:"Hastalıklar",x:"Peritonitis is a serious inflammation of the abdominal lining."},
  {e:"atherosclerosis",t:"ateroskleroz / damar sertliği",c:"Hastalıklar",x:"Atherosclerosis narrows arteries due to plaque buildup."},
  {e:"arrhythmia",t:"aritmi",c:"Hastalıklar",x:"Cardiac arrhythmia involves irregular heartbeats."},
  {e:"ischemia",t:"iskemi",c:"Hastalıklar",x:"Myocardial ischemia occurs when blood flow to the heart is reduced."},
  {e:"stenosis",t:"stenoz / darlık",c:"Hastalıklar",x:"Aortic stenosis restricts blood flow from the heart."},
  {e:"hypoglycemia",t:"hipoglisemi",c:"Hastalıklar",x:"Hypoglycemia causes dangerously low blood sugar levels."},
  {e:"hyperglycemia",t:"hiperglisemi",c:"Hastalıklar",x:"Persistent hyperglycemia can damage blood vessels."},
  {e:"hypothyroidism",t:"hipotiroidizm",c:"Hastalıklar",x:"Hypothyroidism slows down the body's metabolic processes."},
  {e:"hyperthyroidism",t:"hipertiroidizm",c:"Hastalıklar",x:"Hyperthyroidism causes an overproduction of thyroid hormones."},

  // === TEDAVI & ILAC (70+) ===
  {e:"antibiotic",t:"antibiyotik",c:"Tedavi & İlaç",x:"Antibiotics are used to treat bacterial infections."},
  {e:"analgesic",t:"ağrı kesici",c:"Tedavi & İlaç",x:"Analgesics relieve pain without causing loss of consciousness."},
  {e:"anesthesia",t:"anestezi",c:"Tedavi & İlaç",x:"General anesthesia renders the patient completely unconscious."},
  {e:"chemotherapy",t:"kemoterapi",c:"Tedavi & İlaç",x:"Chemotherapy uses drugs to destroy cancer cells."},
  {e:"radiation therapy",t:"radyoterapi",c:"Tedavi & İlaç",x:"Radiation therapy targets and kills cancer cells."},
  {e:"immunotherapy",t:"immünoterapi",c:"Tedavi & İlaç",x:"Immunotherapy enhances the body's immune response against cancer."},
  {e:"vaccine",t:"aşı",c:"Tedavi & İlaç",x:"Vaccines stimulate the immune system to produce antibodies."},
  {e:"dosage",t:"dozaj / doz miktarı",c:"Tedavi & İlaç",x:"The correct dosage depends on the patient's weight and age."},
  {e:"prescription",t:"reçete",c:"Tedavi & İlaç",x:"Some medications require a doctor's prescription."},
  {e:"side effect",t:"yan etki",c:"Tedavi & İlaç",x:"Drowsiness is a common side effect of antihistamines."},
  {e:"adverse reaction",t:"ters reaksiyon / advers etki",c:"Tedavi & İlaç",x:"Adverse drug reactions should be reported immediately."},
  {e:"drug interaction",t:"ilaç etkileşimi",c:"Tedavi & İlaç",x:"Drug interactions can reduce or increase a medication's effect."},
  {e:"anti-inflammatory",t:"antienflamatuar",c:"Tedavi & İlaç",x:"Anti-inflammatory drugs reduce swelling and pain."},
  {e:"antiviral",t:"antiviral",c:"Tedavi & İlaç",x:"Antiviral medications can shorten the duration of the flu."},
  {e:"antifungal",t:"antifungal",c:"Tedavi & İlaç",x:"Antifungal creams treat skin infections caused by fungi."},
  {e:"steroid",t:"steroid",c:"Tedavi & İlaç",x:"Corticosteroids are used to reduce severe inflammation."},
  {e:"anticoagulant",t:"antikoagülan / kan sulandırıcı",c:"Tedavi & İlaç",x:"Anticoagulants prevent blood clots from forming."},
  {e:"diuretic",t:"diüretik / idrar söktürücü",c:"Tedavi & İlaç",x:"Diuretics help the body eliminate excess fluid."},
  {e:"sedative",t:"sakinleştirici",c:"Tedavi & İlaç",x:"Sedatives are prescribed for severe anxiety and insomnia."},
  {e:"antidepressant",t:"antidepresan",c:"Tedavi & İlaç",x:"Antidepressants help regulate mood and reduce depression."},
  {e:"insulin",t:"insülin",c:"Tedavi & İlaç",x:"Insulin injections are essential for type 1 diabetes patients."},
  {e:"rehabilitation",t:"rehabilitasyon",c:"Tedavi & İlaç",x:"Physical rehabilitation helps patients regain mobility."},
  {e:"physiotherapy",t:"fizyoterapi",c:"Tedavi & İlaç",x:"Physiotherapy is often recommended after joint surgery."},
  {e:"transplantation",t:"nakil / transplantasyon",c:"Tedavi & İlaç",x:"Organ transplantation can save the lives of critically ill patients."},
  {e:"dialysis",t:"diyaliz",c:"Tedavi & İlaç",x:"Dialysis filters waste from the blood when kidneys fail."},
  {e:"blood transfusion",t:"kan nakli",c:"Tedavi & İlaç",x:"A blood transfusion replaces lost blood during surgery."},
  {e:"intravenous (IV)",t:"damar içi",c:"Tedavi & İlaç",x:"Fluids are administered intravenously to dehydrated patients."},
  {e:"intramuscular",t:"kas içi",c:"Tedavi & İlaç",x:"Some vaccines are given via intramuscular injection."},
  {e:"subcutaneous",t:"deri altı",c:"Tedavi & İlaç",x:"Insulin is typically administered by subcutaneous injection."},
  {e:"topical",t:"topikal / bölgesel",c:"Tedavi & İlaç",x:"Topical ointments are applied directly to the skin."},
  {e:"palliative care",t:"palyatif bakım",c:"Tedavi & İlaç",x:"Palliative care focuses on improving quality of life."},
  {e:"prophylaxis",t:"profilaksi / önleyici tedavi",c:"Tedavi & İlaç",x:"Antibiotic prophylaxis prevents infection before surgery."},
  {e:"prognosis",t:"prognoz / hastalık seyri",c:"Tedavi & İlaç",x:"The prognosis for early-stage cancer is generally favorable."},
  {e:"placebo",t:"plasebo",c:"Tedavi & İlaç",x:"A placebo contains no active medication but may still improve symptoms."},
  {e:"clinical trial",t:"klinik deneme",c:"Tedavi & İlaç",x:"Clinical trials test the safety and efficacy of new drugs."},
  {e:"over-the-counter",t:"reçetesiz ilaç",c:"Tedavi & İlaç",x:"Aspirin is available as an over-the-counter medication."},
  {e:"generic drug",t:"jenerik ilaç",c:"Tedavi & İlaç",x:"Generic drugs are equivalent to brand-name medications."},
  {e:"antimicrobial",t:"antimikrobiyal",c:"Tedavi & İlaç",x:"Antimicrobial agents kill or inhibit the growth of microorganisms."},
  {e:"bronchodilator",t:"bronkodilatör",c:"Tedavi & İlaç",x:"Bronchodilators open up the airways in asthma patients."},
  {e:"antihistamine",t:"antihistamin",c:"Tedavi & İlaç",x:"Antihistamines are commonly used to treat allergy symptoms."},
  {e:"antipyretic",t:"ateş düşürücü",c:"Tedavi & İlaç",x:"Acetaminophen is a widely used antipyretic drug."},
  {e:"antiseptic",t:"antiseptik",c:"Tedavi & İlaç",x:"Antiseptic solutions are applied to wounds to prevent infection."},
  {e:"defibrillator",t:"defibrilatör",c:"Tedavi & İlaç",x:"A defibrillator delivers an electric shock to restore normal heart rhythm."},
  {e:"ventilator",t:"solunum cihazı",c:"Tedavi & İlaç",x:"Critically ill patients may need a ventilator to breathe."},
  {e:"catheter",t:"kateter",c:"Tedavi & İlaç",x:"A urinary catheter is used to drain urine from the bladder."},

  // === FIZYOLOJI (60+) ===
  {e:"metabolism",t:"metabolizma",c:"Fizyoloji",x:"Metabolism converts food into energy for cellular processes."},
  {e:"homeostasis",t:"homeostaz",c:"Fizyoloji",x:"Homeostasis maintains the body's internal stability."},
  {e:"immune response",t:"bağışıklık yanıtı",c:"Fizyoloji",x:"The immune response protects the body against pathogens."},
  {e:"antibody",t:"antikor",c:"Fizyoloji",x:"Antibodies are produced by the immune system to fight infections."},
  {e:"antigen",t:"antijen",c:"Fizyoloji",x:"An antigen triggers the production of antibodies."},
  {e:"hormone",t:"hormon",c:"Fizyoloji",x:"Hormones regulate many physiological processes in the body."},
  {e:"enzyme",t:"enzim",c:"Fizyoloji",x:"Enzymes catalyze biochemical reactions in the body."},
  {e:"protein synthesis",t:"protein sentezi",c:"Fizyoloji",x:"Protein synthesis occurs in the ribosomes of cells."},
  {e:"blood pressure",t:"kan basıncı",c:"Fizyoloji",x:"High blood pressure is a risk factor for heart disease."},
  {e:"heart rate",t:"kalp hızı / nabız",c:"Fizyoloji",x:"A resting heart rate of 60-100 beats per minute is normal."},
  {e:"blood glucose",t:"kan şekeri",c:"Fizyoloji",x:"Blood glucose levels rise after eating carbohydrates."},
  {e:"cholesterol",t:"kolesterol",c:"Fizyoloji",x:"High cholesterol increases the risk of atherosclerosis."},
  {e:"respiration",t:"solunum",c:"Fizyoloji",x:"Cellular respiration produces energy in the form of ATP."},
  {e:"circulation",t:"dolaşım",c:"Fizyoloji",x:"Blood circulation delivers oxygen and nutrients to cells."},
  {e:"digestion",t:"sindirim",c:"Fizyoloji",x:"Digestion breaks down food into absorbable nutrients."},
  {e:"absorption",t:"emilim",c:"Fizyoloji",x:"Nutrient absorption primarily occurs in the small intestine."},
  {e:"excretion",t:"boşaltım / atılım",c:"Fizyoloji",x:"The kidneys are the primary organs of excretion."},
  {e:"secretion",t:"salgılama",c:"Fizyoloji",x:"Gastric secretion aids in the digestion of food."},
  {e:"ovulation",t:"yumurtlama",c:"Fizyoloji",x:"Ovulation occurs approximately midway through the menstrual cycle."},
  {e:"fertilization",t:"döllenme",c:"Fizyoloji",x:"Fertilization takes place in the fallopian tube."},
  {e:"gestation",t:"gebelik süresi",c:"Fizyoloji",x:"Human gestation lasts approximately 40 weeks."},
  {e:"pulse",t:"nabız",c:"Fizyoloji",x:"A weak pulse may indicate low blood pressure or shock."},
  {e:"reflex",t:"refleks",c:"Fizyoloji",x:"The knee-jerk reflex tests the function of the spinal cord."},
  {e:"stimulus",t:"uyarıcı / uyaran",c:"Fizyoloji",x:"A stimulus triggers a response in the nervous system."},
  {e:"coagulation",t:"pıhtılaşma",c:"Fizyoloji",x:"Blood coagulation prevents excessive bleeding after injury."},
  {e:"inflammation response",t:"enflamasyon yanıtı",c:"Fizyoloji",x:"The inflammation response helps isolate and eliminate pathogens."},
  {e:"oxygen saturation",t:"oksijen saturasyonu",c:"Fizyoloji",x:"Oxygen saturation below 90% may require supplemental oxygen."},
  {e:"body mass index (BMI)",t:"vücut kitle indeksi (VKİ)",c:"Fizyoloji",x:"A BMI over 30 is classified as obese."},
  {e:"basal metabolic rate",t:"bazal metabolizma hızı",c:"Fizyoloji",x:"Basal metabolic rate represents the minimum energy expenditure at rest."},
  {e:"electrolyte",t:"elektrolit",c:"Fizyoloji",x:"Electrolyte imbalances can cause muscle cramps and weakness."},
  {e:"pH balance",t:"pH dengesi",c:"Fizyoloji",x:"The body maintains a blood pH balance between 7.35 and 7.45."},
  {e:"neurotransmitter",t:"nörotransmiter",c:"Fizyoloji",x:"Serotonin is a neurotransmitter that regulates mood."},
  {e:"adrenaline",t:"adrenalin",c:"Fizyoloji",x:"Adrenaline prepares the body for the fight-or-flight response."},
  {e:"cortisol",t:"kortizol",c:"Fizyoloji",x:"Elevated cortisol levels are associated with chronic stress."},
  {e:"estrogen",t:"östrojen",c:"Fizyoloji",x:"Estrogen plays a key role in female reproductive health."},
  {e:"testosterone",t:"testosteron",c:"Fizyoloji",x:"Testosterone is the primary male sex hormone."},
  {e:"melatonin",t:"melatonin",c:"Fizyoloji",x:"Melatonin regulates the sleep-wake cycle."},
  {e:"gene expression",t:"gen ifadesi",c:"Fizyoloji",x:"Gene expression determines which proteins a cell produces."},
  {e:"DNA replication",t:"DNA replikasyonu",c:"Fizyoloji",x:"DNA replication occurs before cell division."},
  {e:"mitosis",t:"mitoz bölünme",c:"Fizyoloji",x:"Mitosis produces two identical daughter cells."},
  {e:"apoptosis",t:"apoptoz / programlı hücre ölümü",c:"Fizyoloji",x:"Apoptosis eliminates damaged or unnecessary cells."},
  {e:"stem cell",t:"kök hücre",c:"Fizyoloji",x:"Stem cells can differentiate into various specialized cell types."},

  // === CERRAHI (55+) ===
  {e:"surgery",t:"cerrahi / ameliyat",c:"Cerrahi",x:"The patient underwent surgery to remove the tumor."},
  {e:"incision",t:"kesi / insizyon",c:"Cerrahi",x:"The surgeon made a small incision in the abdomen."},
  {e:"suture",t:"dikiş",c:"Cerrahi",x:"The wound was closed with absorbable sutures."},
  {e:"laparoscopy",t:"laparoskopi",c:"Cerrahi",x:"Laparoscopy is a minimally invasive surgical technique."},
  {e:"biopsy",t:"biyopsi",c:"Cerrahi",x:"A biopsy confirmed the presence of cancer cells."},
  {e:"amputation",t:"amputasyon",c:"Cerrahi",x:"Amputation was necessary due to severe tissue damage."},
  {e:"graft",t:"greft / doku nakli",c:"Cerrahi",x:"A skin graft was performed on the burn patient."},
  {e:"bypass surgery",t:"baypas ameliyatı",c:"Cerrahi",x:"Coronary bypass surgery restores blood flow to the heart."},
  {e:"cesarean section",t:"sezaryen",c:"Cerrahi",x:"A cesarean section is performed when vaginal delivery is risky."},
  {e:"mastectomy",t:"mastektomi / meme alınması",c:"Cerrahi",x:"A mastectomy may be recommended for breast cancer patients."},
  {e:"appendectomy",t:"apendektomi",c:"Cerrahi",x:"An appendectomy removes the inflamed appendix."},
  {e:"colostomy",t:"kolostomi",c:"Cerrahi",x:"A colostomy diverts the colon to an opening in the abdomen."},
  {e:"tracheotomy",t:"trakeotomi",c:"Cerrahi",x:"A tracheotomy creates an airway opening in the trachea."},
  {e:"angioplasty",t:"anjiyoplasti",c:"Cerrahi",x:"Angioplasty widens narrowed or blocked arteries."},
  {e:"stent",t:"stent",c:"Cerrahi",x:"A stent keeps the artery open after angioplasty."},
  {e:"prosthesis",t:"protez",c:"Cerrahi",x:"A hip prosthesis replaces a damaged hip joint."},
  {e:"implant",t:"implant",c:"Cerrahi",x:"Dental implants replace missing teeth permanently."},
  {e:"endoscopy",t:"endoskopi",c:"Cerrahi",x:"Endoscopy allows doctors to examine the digestive tract."},
  {e:"arthroscopy",t:"artroskopi",c:"Cerrahi",x:"Arthroscopy is used to diagnose and treat joint problems."},
  {e:"resection",t:"rezeksiyon / çıkarma",c:"Cerrahi",x:"Tumor resection removes cancerous tissue from the body."},
  {e:"excision",t:"eksizyon / kesip çıkarma",c:"Cerrahi",x:"Surgical excision of the lesion was performed under local anesthesia."},
  {e:"debridement",t:"debridman",c:"Cerrahi",x:"Wound debridement removes dead tissue to promote healing."},
  {e:"cauterization",t:"koterize etme",c:"Cerrahi",x:"Cauterization stops bleeding by burning the tissue."},
  {e:"tourniquet",t:"turnike",c:"Cerrahi",x:"A tourniquet is applied to control severe bleeding."},
  {e:"sterile",t:"steril",c:"Cerrahi",x:"All surgical instruments must be sterile to prevent infection."},
  {e:"postoperative",t:"ameliyat sonrası",c:"Cerrahi",x:"Postoperative care is crucial for a successful recovery."},
  {e:"preoperative",t:"ameliyat öncesi",c:"Cerrahi",x:"Preoperative tests help assess the patient's fitness for surgery."},
  {e:"complication",t:"komplikasyon",c:"Cerrahi",x:"Surgical complications include infection and excessive bleeding."},
  {e:"hemorrhaging",t:"kanama",c:"Cerrahi",x:"Hemorrhaging during surgery requires immediate intervention."},
  {e:"adhesion",t:"adezyon / yapışıklık",c:"Cerrahi",x:"Adhesions may form after abdominal surgery."},
  {e:"minimally invasive",t:"minimal invaziv",c:"Cerrahi",x:"Minimally invasive surgery reduces recovery time significantly."},
  {e:"open surgery",t:"açık cerrahi",c:"Cerrahi",x:"Open surgery may be necessary for complex tumor removal."},
  {e:"operating room",t:"ameliyathane",c:"Cerrahi",x:"The operating room must meet strict hygiene standards."},
  {e:"scalpel",t:"neşter / bistüri",c:"Cerrahi",x:"The surgeon used a scalpel to make the initial incision."},
  {e:"forceps",t:"forseps",c:"Cerrahi",x:"Forceps are used to hold tissue during surgery."},

  // === TANI & TESHIS (55+) ===
  {e:"diagnosis",t:"tanı / teşhis",c:"Tanı & Teşhis",x:"Early diagnosis of cancer improves survival rates."},
  {e:"symptom",t:"semptom / belirti",c:"Tanı & Teşhis",x:"Fever is a common symptom of many infections."},
  {e:"sign",t:"bulgu",c:"Tanı & Teşhis",x:"Elevated blood pressure is a sign of hypertension."},
  {e:"screening",t:"tarama",c:"Tanı & Teşhis",x:"Cancer screening can detect tumors at an early stage."},
  {e:"prognosis",t:"prognoz / öngörü",c:"Tanı & Teşhis",x:"The prognosis depends on the stage of the disease."},
  {e:"MRI scan",t:"MR taraması",c:"Tanı & Teşhis",x:"An MRI scan provides detailed images of soft tissues."},
  {e:"CT scan",t:"BT taraması",c:"Tanı & Teşhis",x:"A CT scan combines X-rays to create cross-sectional images."},
  {e:"X-ray",t:"röntgen",c:"Tanı & Teşhis",x:"An X-ray revealed a fracture in the patient's wrist."},
  {e:"ultrasound",t:"ultrason",c:"Tanı & Teşhis",x:"Ultrasound imaging is commonly used during pregnancy."},
  {e:"blood test",t:"kan testi",c:"Tanı & Teşhis",x:"A blood test can reveal infections, anemia, and organ function."},
  {e:"urinalysis",t:"idrar tahlili",c:"Tanı & Teşhis",x:"Urinalysis helps detect kidney disease and urinary infections."},
  {e:"pathology",t:"patoloji",c:"Tanı & Teşhis",x:"Pathology reports determine whether a tumor is malignant."},
  {e:"laboratory findings",t:"laboratuvar bulguları",c:"Tanı & Teşhis",x:"Laboratory findings confirmed the suspected diagnosis."},
  {e:"differential diagnosis",t:"ayırıcı tanı",c:"Tanı & Teşhis",x:"Differential diagnosis considers all possible conditions."},
  {e:"misdiagnosis",t:"yanlış tanı",c:"Tanı & Teşhis",x:"Misdiagnosis can lead to inappropriate treatment."},
  {e:"electrocardiogram (ECG)",t:"elektrokardiyogram (EKG)",c:"Tanı & Teşhis",x:"An ECG records the electrical activity of the heart."},
  {e:"electroencephalogram (EEG)",t:"elektroensefalogram (EEG)",c:"Tanı & Teşhis",x:"An EEG measures brain wave patterns."},
  {e:"colonoscopy",t:"kolonoskopi",c:"Tanı & Teşhis",x:"A colonoscopy examines the lining of the large intestine."},
  {e:"mammography",t:"mamografi",c:"Tanı & Teşhis",x:"Regular mammography can detect breast cancer early."},
  {e:"spirometry",t:"spirometri",c:"Tanı & Teşhis",x:"Spirometry measures how well the lungs are functioning."},
  {e:"culture test",t:"kültür testi",c:"Tanı & Teşhis",x:"A culture test identifies the specific bacteria causing infection."},
  {e:"biopsy result",t:"biyopsi sonucu",c:"Tanı & Teşhis",x:"The biopsy result showed no evidence of malignancy."},
  {e:"vital signs",t:"yaşamsal bulgular",c:"Tanı & Teşhis",x:"Vital signs include temperature, pulse, respiration, and blood pressure."},
  {e:"medical history",t:"tıbbi öykü / anamnez",c:"Tanı & Teşhis",x:"A thorough medical history helps guide accurate diagnosis."},
  {e:"physical examination",t:"fizik muayene",c:"Tanı & Teşhis",x:"The physical examination revealed tenderness in the abdomen."},
  {e:"auscultation",t:"oskültasyon / dinleme",c:"Tanı & Teşhis",x:"Auscultation of the lungs revealed abnormal breathing sounds."},
  {e:"palpation",t:"palpasyon / elle muayene",c:"Tanı & Teşhis",x:"Palpation of the abdomen detected an enlarged liver."},
  {e:"percussion",t:"perküsyon / vurarak muayene",c:"Tanı & Teşhis",x:"Chest percussion helps assess fluid in the lungs."},
  {e:"biomarker",t:"biyobelirteç",c:"Tanı & Teşhis",x:"Biomarkers can indicate the presence or progression of disease."},
  {e:"genetic testing",t:"genetik test",c:"Tanı & Teşhis",x:"Genetic testing can identify inherited disease risks."},
  {e:"PET scan",t:"PET taraması",c:"Tanı & Teşhis",x:"A PET scan detects metabolically active areas such as tumors."},

  // === HALK SAGLIGI (55+) ===
  {e:"public health",t:"halk sağlığı",c:"Halk Sağlığı",x:"Public health measures can prevent disease outbreaks."},
  {e:"prevalence",t:"yaygınlık / prevalans",c:"Halk Sağlığı",x:"The prevalence of diabetes has increased dramatically."},
  {e:"incidence",t:"insidans / görülme sıklığı",c:"Halk Sağlığı",x:"The incidence of new cases peaked during the winter months."},
  {e:"mortality rate",t:"ölüm oranı",c:"Halk Sağlığı",x:"The mortality rate from infectious diseases has declined globally."},
  {e:"morbidity",t:"hastalık oranı / morbidite",c:"Halk Sağlığı",x:"Morbidity data helps assess the burden of disease."},
  {e:"life expectancy",t:"yaşam beklentisi",c:"Halk Sağlığı",x:"Life expectancy has increased due to medical advances."},
  {e:"epidemiology",t:"epidemiyoloji",c:"Halk Sağlığı",x:"Epidemiology studies the distribution of diseases in populations."},
  {e:"quarantine",t:"karantina",c:"Halk Sağlığı",x:"Quarantine helps prevent the spread of infectious diseases."},
  {e:"sanitation",t:"hijyen / sanitasyon",c:"Halk Sağlığı",x:"Improved sanitation reduces the transmission of waterborne diseases."},
  {e:"outbreak",t:"salgın başlangıcı",c:"Halk Sağlığı",x:"The disease outbreak was traced to contaminated water."},
  {e:"immunization",t:"bağışıklama",c:"Halk Sağlığı",x:"Childhood immunization prevents many serious diseases."},
  {e:"risk factor",t:"risk faktörü",c:"Halk Sağlığı",x:"Smoking is a major risk factor for lung cancer."},
  {e:"prevention",t:"önleme / korunma",c:"Halk Sağlığı",x:"Disease prevention is more cost-effective than treatment."},
  {e:"pandemic",t:"pandemi",c:"Halk Sağlığı",x:"A pandemic affects people across multiple countries."},
  {e:"epidemic",t:"epidemi / salgın",c:"Halk Sağlığı",x:"An epidemic is a widespread occurrence of disease in a community."},
  {e:"endemic",t:"endemik",c:"Halk Sağlığı",x:"Malaria is endemic in many tropical regions."},
  {e:"surveillance",t:"gözetim / sürveyans",c:"Halk Sağlığı",x:"Disease surveillance monitors the spread of infections."},
  {e:"vector",t:"vektör / taşıyıcı",c:"Halk Sağlığı",x:"Mosquitoes are the primary vector for malaria transmission."},
  {e:"transmission",t:"bulaşma / geçiş",c:"Halk Sağlığı",x:"Airborne transmission is a common route for respiratory viruses."},
  {e:"herd immunity",t:"topluluk bağışıklığı",c:"Halk Sağlığı",x:"Herd immunity protects those who cannot be vaccinated."},
  {e:"contagious",t:"bulaşıcı",c:"Halk Sağlığı",x:"The flu is highly contagious and spreads through droplets."},
  {e:"communicable",t:"bulaşabilir",c:"Halk Sağlığı",x:"Communicable diseases can be transmitted between individuals."},
  {e:"non-communicable",t:"bulaşıcı olmayan",c:"Halk Sağlığı",x:"Non-communicable diseases include diabetes and heart disease."},
  {e:"vaccination campaign",t:"aşı kampanyası",c:"Halk Sağlığı",x:"The vaccination campaign reduced polio cases by 99 percent."},
  {e:"health literacy",t:"sağlık okuryazarlığı",c:"Halk Sağlığı",x:"Health literacy helps individuals make informed health decisions."},
  {e:"health promotion",t:"sağlığı geliştirme",c:"Halk Sağlığı",x:"Health promotion programs encourage healthy lifestyle changes."},
  {e:"clinical guideline",t:"klinik kılavuz",c:"Halk Sağlığı",x:"Clinical guidelines standardize treatment practices."},
  {e:"informed consent",t:"bilgilendirilmiş onam",c:"Halk Sağlığı",x:"Informed consent is required before any medical procedure."},
  {e:"triage",t:"triyaj",c:"Halk Sağlığı",x:"Triage prioritizes patients based on the severity of their condition."},
  {e:"occupational health",t:"iş sağlığı",c:"Halk Sağlığı",x:"Occupational health programs protect workers from hazards."},

  // === GENEL TIP (60+) ===
  {e:"patient",t:"hasta",c:"Genel Tıp",x:"The patient was admitted for further observation."},
  {e:"physician",t:"hekim / doktor",c:"Genel Tıp",x:"A physician must consider all symptoms before making a diagnosis."},
  {e:"surgeon",t:"cerrah",c:"Genel Tıp",x:"The surgeon performed a complex heart operation."},
  {e:"nurse",t:"hemşire",c:"Genel Tıp",x:"The nurse monitored the patient's vital signs every hour."},
  {e:"acute",t:"akut / ani başlangıçlı",c:"Genel Tıp",x:"Acute appendicitis requires immediate surgical intervention."},
  {e:"chronic",t:"kronik / süreğen",c:"Genel Tıp",x:"Chronic back pain affects millions of people worldwide."},
  {e:"congenital",t:"doğuştan / konjenital",c:"Genel Tıp",x:"Congenital heart defects are present at birth."},
  {e:"hereditary",t:"kalıtsal",c:"Genel Tıp",x:"Some cancers have a hereditary component."},
  {e:"lethal",t:"ölümcül",c:"Genel Tıp",x:"Without treatment, the infection can be lethal."},
  {e:"outpatient",t:"ayaktan tedavi",c:"Genel Tıp",x:"The procedure was performed on an outpatient basis."},
  {e:"inpatient",t:"yatan hasta",c:"Genel Tıp",x:"Inpatient care requires an overnight hospital stay."},
  {e:"emergency",t:"acil durum",c:"Genel Tıp",x:"Emergency departments treat life-threatening conditions."},
  {e:"intensive care unit",t:"yoğun bakım ünitesi",c:"Genel Tıp",x:"The patient was transferred to the intensive care unit."},
  {e:"relapse",t:"nüks / tekrarlama",c:"Genel Tıp",x:"Cancer relapse may occur months or years after treatment."},
  {e:"remission",t:"remisyon",c:"Genel Tıp",x:"The patient has been in remission for two years."},
  {e:"etiology",t:"etiyoloji / hastalık nedeni",c:"Genel Tıp",x:"The etiology of the disease remains unknown."},
  {e:"pathogen",t:"patojen / hastalık etkeni",c:"Genel Tıp",x:"Pathogens include bacteria, viruses, and fungi."},
  {e:"specimen",t:"numune / örnek",c:"Genel Tıp",x:"A blood specimen was sent to the laboratory for analysis."},
  {e:"contraindication",t:"kontrendikasyon",c:"Genel Tıp",x:"Aspirin is contraindicated in patients with bleeding disorders."},
  {e:"clinical",t:"klinik",c:"Genel Tıp",x:"Clinical studies provide evidence for medical treatment."},
  {e:"malpractice",t:"tıbbi hata",c:"Genel Tıp",x:"Medical malpractice lawsuits arise from negligent care."},
  {e:"anatomy",t:"anatomi",c:"Genel Tıp",x:"A thorough understanding of anatomy is essential for surgeons."},
  {e:"physiology",t:"fizyoloji",c:"Genel Tıp",x:"Physiology studies how the body's organs and systems function."},
  {e:"pharmacology",t:"farmakoloji",c:"Genel Tıp",x:"Pharmacology examines the effects of drugs on the body."},
  {e:"pediatrics",t:"pediatri / çocuk hastalıkları",c:"Genel Tıp",x:"Pediatrics focuses on the medical care of infants and children."},
  {e:"geriatrics",t:"geriatri / yaşlı hastalıkları",c:"Genel Tıp",x:"Geriatrics addresses health issues specific to elderly patients."},
  {e:"oncology",t:"onkoloji",c:"Genel Tıp",x:"Oncology is the branch of medicine that treats cancer."},
  {e:"cardiology",t:"kardiyoloji",c:"Genel Tıp",x:"Cardiology deals with disorders of the heart."},
  {e:"neurology",t:"nöroloji",c:"Genel Tıp",x:"Neurology treats diseases of the nervous system."},
  {e:"dermatology",t:"dermatoloji",c:"Genel Tıp",x:"Dermatology focuses on skin disorders and conditions."},
  {e:"orthopedics",t:"ortopedi",c:"Genel Tıp",x:"Orthopedics treats injuries of the musculoskeletal system."},
  {e:"ophthalmology",t:"göz hastalıkları",c:"Genel Tıp",x:"Ophthalmology deals with diseases and surgery of the eye."},
  {e:"psychiatry",t:"psikiyatri",c:"Genel Tıp",x:"Psychiatry treats mental, emotional, and behavioral disorders."},
  {e:"radiology",t:"radyoloji",c:"Genel Tıp",x:"Radiology uses imaging techniques to diagnose diseases."},
  {e:"anesthesiology",t:"anesteziyoloji",c:"Genel Tıp",x:"Anesthesiology ensures patients remain pain-free during surgery."},
  {e:"urology",t:"üroloji",c:"Genel Tıp",x:"Urology treats conditions of the urinary tract."},
  {e:"gynecology",t:"jinekoloji",c:"Genel Tıp",x:"Gynecology focuses on the female reproductive system."},
  {e:"obstetrics",t:"doğum bilimi",c:"Genel Tıp",x:"Obstetrics manages pregnancy, labor, and childbirth."},
  {e:"pulmonology",t:"göğüs hastalıkları",c:"Genel Tıp",x:"Pulmonology specializes in diseases of the respiratory system."},
  {e:"gastroenterology",t:"gastroenteroloji",c:"Genel Tıp",x:"Gastroenterology treats disorders of the digestive system."},
  {e:"endocrinology",t:"endokrinoloji",c:"Genel Tıp",x:"Endocrinology deals with hormonal imbalances and disorders."},
  {e:"rheumatology",t:"romatoloji",c:"Genel Tıp",x:"Rheumatology treats autoimmune and inflammatory joint diseases."},
  {e:"hematology",t:"hematoloji",c:"Genel Tıp",x:"Hematology deals with diseases of the blood."},
  {e:"nephrology",t:"nefroloji",c:"Genel Tıp",x:"Nephrology focuses on kidney diseases and their treatment."},
  {e:"palliative",t:"palyatif",c:"Genel Tıp",x:"Palliative medicine aims to relieve suffering in terminal illness."},
  {e:"prognosis",t:"prognoz",c:"Genel Tıp",x:"The prognosis for this condition is generally favorable."},
  {e:"chronic pain",t:"kronik ağrı",c:"Genel Tıp",x:"Chronic pain management often requires a multidisciplinary approach."},
  {e:"wound healing",t:"yara iyileşmesi",c:"Genel Tıp",x:"Wound healing is a complex biological process."},
  {e:"infection control",t:"enfeksiyon kontrolü",c:"Genel Tıp",x:"Strict infection control measures are essential in hospitals."},
  {e:"evidence-based medicine",t:"kanıta dayalı tıp",c:"Genel Tıp",x:"Evidence-based medicine integrates clinical expertise with research."},
  {e:"medical ethics",t:"tıp etiği",c:"Genel Tıp",x:"Medical ethics guides decision-making in patient care."},
  {e:"telemedicine",t:"teletıp",c:"Genel Tıp",x:"Telemedicine enables remote consultations via video calls."},
  {e:"primary care",t:"birinci basamak sağlık hizmeti",c:"Genel Tıp",x:"Primary care physicians manage general health conditions."},
];

// JSON dosyasi olarak kaydet
const outPath = path.join(__dirname, 'assets', 'health_terms.json');
fs.writeFileSync(outPath, JSON.stringify(terms, null, 0), 'utf8');
console.log('Toplam saglik terimi: ' + terms.length);
console.log('Dosya kaydedildi: assets/health_terms.json');

// Kategorilere gore say
const cats = {};
for (const t of terms) {
  cats[t.c] = (cats[t.c] || 0) + 1;
}
console.log('\nKategoriler:');
for (const [k, v] of Object.entries(cats)) {
  console.log('  ' + k + ': ' + v);
}
